My Application: CRenderPos Class Reference
CRenderPos Class Reference
#include <RenderPos.h>
Public Member Functions
CRenderPos (void)
~CRenderPos (void)
void setRotation (float a, int x, int y, int z)
void setTranslation (float x, float y, float z)
void setScale (float x, float y, float z)
void setName (string name)
float getRotation (void)
float getTranslationX (void)
float getTranslationY (void)
float getTranslationZ (void)
int getRX (void)
int getRY (void)
int getRZ (void)
float getScaleX (void)
float getScaleY (void)
float getScaleZ (void)
string getName (void)
Private Attributes
float rotation
float translationX
float translationY
float translationZ
int RX
int RY
int RZ
float scaleX
float scaleY
float scaleZ
string modelName
Detailed Description
Definition at line 7 of file RenderPos.h.
Constructor & Destructor Documentation
CRenderPos::CRenderPos (void)
Definition at line 4 of file RenderPos.cpp.
CRenderPos::~CRenderPos (void)
Definition at line 9 of file RenderPos.cpp.
Member Function Documentation
string CRenderPos::getName (void)
Definition at line 90 of file RenderPos.cpp.
References modelName.
Referenced by SP2::Init().
float CRenderPos::getRotation (void)
Definition at line 40 of file RenderPos.cpp.
References rotation.
Referenced by SP2::RenderBuilding(), SP2::RenderCashier(), SP2::RenderCashierModel(), SP2::RenderFridge(), SP2::RenderShelves(), SP2::RenderWorld(), and SP2::Trolley().
int CRenderPos::getRX (void)
Definition at line 45 of file RenderPos.cpp.
References RX.
Referenced by SP2::RenderBuilding(), SP2::RenderCashier(), SP2::RenderCashierModel(), SP2::RenderCharacter(), SP2::RenderFridge(), SP2::RenderShelves(), SP2::RenderWorld(), SP2::Trolley(), and SP2::TrolleyUpdate().
int CRenderPos::getRY (void)
Definition at line 50 of file RenderPos.cpp.
References RY.
Referenced by SP2::RenderBuilding(), SP2::RenderCashier(), SP2::RenderCashierModel(), SP2::RenderCharacter(), SP2::RenderFridge(), SP2::RenderShelves(), SP2::RenderWorld(), SP2::Trolley(), and SP2::TrolleyUpdate().
int CRenderPos::getRZ (void)
Definition at line 55 of file RenderPos.cpp.
References RZ.
Referenced by SP2::RenderBuilding(), SP2::RenderCashier(), SP2::RenderCashierModel(), SP2::RenderCharacter(), SP2::RenderFridge(), SP2::RenderShelves(), SP2::RenderWorld(), SP2::Trolley(), and SP2::TrolleyUpdate().
float CRenderPos::getScaleX (void)
Definition at line 60 of file RenderPos.cpp.
References scaleX.
Referenced by SP2::RenderBuilding(), SP2::RenderCashier(), SP2::RenderCashierModel(), SP2::RenderCharacter(), SP2::RenderFridge(), SP2::RenderShelves(), SP2::RenderWorld(), SP2::Trolley(), and SP2::TrolleyUpdate().
float CRenderPos::getScaleY (void)
Definition at line 65 of file RenderPos.cpp.
References scaleY.
Referenced by SP2::RenderBuilding(), SP2::RenderCashier(), SP2::RenderCashierModel(), SP2::RenderCharacter(), SP2::RenderFridge(), SP2::RenderShelves(), SP2::RenderWorld(), SP2::Trolley(), and SP2::TrolleyUpdate().
float CRenderPos::getScaleZ (void)
Definition at line 70 of file RenderPos.cpp.
References scaleZ.
Referenced by SP2::RenderBuilding(), SP2::RenderCashier(), SP2::RenderCashierModel(), SP2::RenderCharacter(), SP2::RenderFridge(), SP2::RenderShelves(), SP2::RenderWorld(), SP2::Trolley(), and SP2::TrolleyUpdate().
float CRenderPos::getTranslationX (void)
Definition at line 75 of file RenderPos.cpp.
References translationX.
Referenced by SP2::BoundsCheck(), SP2::BoundsCheckTrolley(), SP2::BulletCollision(), SP2::BulletCollisionEnemy(), SP2::CheckOut(), SP2::Init(), SP2::RenderBuilding(), SP2::RenderCashier(), SP2::RenderCashierModel(), SP2::RenderFridge(), SP2::RenderScreenUI(), SP2::RenderShelves(), SP2::RenderWorld(), SP2::Trolley(), and SP2::UIupdates().
float CRenderPos::getTranslationY (void)
Definition at line 80 of file RenderPos.cpp.
References translationY.
Referenced by SP2::CheckOut(), SP2::Init(), SP2::RenderBuilding(), SP2::RenderCashier(), SP2::RenderCashierModel(), SP2::RenderCharacter(), SP2::RenderFridge(), SP2::RenderShelves(), SP2::RenderWorld(), SP2::Trolley(), SP2::TrolleyUpdate(), and SP2::UIupdates().
float CRenderPos::getTranslationZ (void)
Definition at line 85 of file RenderPos.cpp.
References translationZ.
Referenced by SP2::BoundsCheck(), SP2::BoundsCheckTrolley(), SP2::BulletCollision(), SP2::BulletCollisionEnemy(), SP2::CheckOut(), SP2::Init(), SP2::RenderBuilding(), SP2::RenderCashier(), SP2::RenderCashierModel(), SP2::RenderFridge(), SP2::RenderScreenUI(), SP2::RenderShelves(), SP2::RenderWorld(), SP2::Trolley(), and SP2::UIupdates().
void CRenderPos::setName (string name)
Definition at line 35 of file RenderPos.cpp.
References modelName.
Referenced by CReadFromText::ReadTextFile().
void CRenderPos::setRotation (float a, int x, int y, int z)
Definition at line 13 of file RenderPos.cpp.
References rotation, RX, RY, and RZ.
Referenced by CReadFromText::ReadTextFile().
void CRenderPos::setScale (float x, float y, float z)
Definition at line 28 of file RenderPos.cpp.
References scaleX, scaleY, and scaleZ.
Referenced by CReadFromText::ReadTextFile().
void CRenderPos::setTranslation (float x, float y, float z)
Definition at line 21 of file RenderPos.cpp.
References translationX, translationY, and translationZ.
Referenced by CReadFromText::ReadTextFile().
Field Documentation
string CRenderPos::modelName private
Definition at line 20 of file RenderPos.h.
Referenced by getName(), and setName().
float CRenderPos::rotation private
Definition at line 10 of file RenderPos.h.
Referenced by getRotation(), and setRotation().
int CRenderPos::RX private
Definition at line 14 of file RenderPos.h.
Referenced by getRX(), and setRotation().
int CRenderPos::RY private
Definition at line 15 of file RenderPos.h.
Referenced by getRY(), and setRotation().
int CRenderPos::RZ private
Definition at line 16 of file RenderPos.h.
Referenced by getRZ(), and setRotation().
float CRenderPos::scaleX private
Definition at line 17 of file RenderPos.h.
Referenced by getScaleX(), and setScale().
float CRenderPos::scaleY private
Definition at line 18 of file RenderPos.h.
Referenced by getScaleY(), and setScale().
float CRenderPos::scaleZ private
Definition at line 19 of file RenderPos.h.
Referenced by getScaleZ(), and setScale().
float CRenderPos::translationX private
Definition at line 11 of file RenderPos.h.
Referenced by getTranslationX(), and setTranslation().
float CRenderPos::translationY private
Definition at line 12 of file RenderPos.h.
Referenced by getTranslationY(), and setTranslation().
float CRenderPos::translationZ private
Definition at line 13 of file RenderPos.h.
Referenced by getTranslationZ(), and setTranslation().
The documentation for this class was generated from the following files:
MyGraphics/Source/RenderPos.h
MyGraphics/Source/RenderPos.cpp