My Application: Csounds Class Reference
Csounds Class Reference
#include <Csounds.h>
Public Member Functions
Csounds (void)
~Csounds (void)
bool MainMusic ()
bool Explosion ()
bool Bullet ()
bool MetalClank ()
bool CheckOut ()
bool Reload ()
Private Attributes
ISoundEngine * engine
Detailed Description
Definition at line 7 of file Csounds.h.
Constructor & Destructor Documentation
Csounds::Csounds (void)
Definition at line 4 of file Csounds.cpp.
References irrklang::createIrrKlangDevice(), and engine.
Csounds::~Csounds (void)
Definition at line 10 of file Csounds.cpp.
References irrklang::IRefCounted::drop(), and engine.
Referenced by SP2::Exit().
Member Function Documentation
bool Csounds::Bullet ()
Definition at line 27 of file Csounds.cpp.
References engine, and irrklang::ISoundEngine::play3D().
Referenced by SP2::Update().
bool Csounds::CheckOut ()
Definition at line 39 of file Csounds.cpp.
References engine, and irrklang::ISoundEngine::play3D().
Referenced by SP2::CheckOut().
bool Csounds::Explosion ()
Definition at line 21 of file Csounds.cpp.
References engine, and irrklang::ISoundEngine::play3D().
Referenced by SP2::EscapeSteal().
bool Csounds::MainMusic ()
Definition at line 15 of file Csounds.cpp.
References engine, and irrklang::ISoundEngine::play3D().
Referenced by SP2::Init().
bool Csounds::MetalClank ()
Definition at line 33 of file Csounds.cpp.
References engine, and irrklang::ISoundEngine::play3D().
Referenced by SP2::MenuUpdate().
bool Csounds::Reload ()
Definition at line 45 of file Csounds.cpp.
References engine, and irrklang::ISoundEngine::play3D().
Referenced by SP2::Update().
Field Documentation
ISoundEngine* Csounds::engine private
Definition at line 10 of file Csounds.h.
Referenced by Bullet(), CheckOut(), Csounds(), Explosion(), MainMusic(), MetalClank(), Reload(), and ~Csounds().
The documentation for this class was generated from the following files:
MyGraphics/Source/Csounds.h
MyGraphics/Source/Csounds.cpp