My Application: CReadFromText Class Reference
CReadFromText Class Reference
#include <ReadFromText.h>
Public Member Functions
CReadFromText (void)
~CReadFromText (void)
CRenderPos * GetRenderPos (const int selection)
CItem * GetRenderPosItem (int selection)
CItem * GetRenderPosPolice (int selection)
void ReadTextFile (const char *filename)
void ReadTextFileItem (const char *filename)
void ReadTextFilePolice (const char *filename)
void ResetData (void)
int ReturnListSize (void)
int ReturnReadListSize (void)
int ReadTextFilePoliceSize (void)
Private Attributes
vector< CRenderPos * > my_list
vector< CItem * > item_list
vector< CItem * > Police_list
Detailed Description
Definition at line 24 of file ReadFromText.h.
Constructor & Destructor Documentation
CReadFromText::CReadFromText (void)
Definition at line 13 of file ReadFromText.cpp.
References my_list.
CReadFromText::~CReadFromText (void)
Definition at line 18 of file ReadFromText.cpp.
References ResetData().
Member Function Documentation
CRenderPos * CReadFromText::GetRenderPos (const int selection)
Definition at line 23 of file ReadFromText.cpp.
References my_list.
Referenced by SP2::BoundsCheck(), SP2::BulletCollision(), SP2::BulletCollisionEnemy(), SP2::CheckOut(), SP2::Init(), SP2::RenderCashier(), SP2::RenderCashierModel(), SP2::RenderCharacter(), SP2::RenderFridge(), SP2::RenderScreenUI(), SP2::RenderShelves(), SP2::RenderWorld(), SP2::Trolley(), SP2::TrolleyUpdate(), and SP2::UIupdates().
CItem * CReadFromText::GetRenderPosItem (int selection)
Definition at line 28 of file ReadFromText.cpp.
References item_list.
Referenced by SP2::BulletCollision(), SP2::BulletCollisionEnemy(), SP2::CheckItem(), SP2::Init(), SP2::NPCShop(), SP2::RenderFNB(), SP2::RenderPolice(), SP2::UIupdates(), and SP2::Update().
CItem * CReadFromText::GetRenderPosPolice (int selection)
Definition at line 33 of file ReadFromText.cpp.
References Police_list.
Referenced by SP2::BulletCollision(), SP2::Init(), SP2::PoliceShoot(), SP2::RenderPolice(), and SP2::Update().
void CReadFromText::ReadTextFile (const char * filename)
Definition at line 51 of file ReadFromText.cpp.
References my_list, ResetData(), CRenderPos::setName(), CRenderPos::setRotation(), CRenderPos::setScale(), and CRenderPos::setTranslation().
Referenced by SP2::Init().
void CReadFromText::ReadTextFileItem (const char * filename)
Definition at line 99 of file ReadFromText.cpp.
References item_list, ResetData(), CItem::setItemAvailable(), CItem::setItemName(), CItem::setItemPrice(), CItem::setItemRotation(), CItem::setItemScale(), and CItem::setItemTranslation().
Referenced by SP2::Init().
void CReadFromText::ReadTextFilePolice (const char * filename)
Definition at line 149 of file ReadFromText.cpp.
References Police_list, ResetData(), CItem::RespawnCD, CItem::setItemAvailable(), CItem::setItemName(), CItem::setItemPrice(), CItem::setItemRotation(), CItem::setItemScale(), CItem::setItemTranslation(), and CItem::ShootCD.
Referenced by SP2::Init().
int CReadFromText::ReadTextFilePoliceSize (void)
Definition at line 211 of file ReadFromText.cpp.
References Police_list.
Referenced by SP2::Init(), SP2::PoliceShoot(), SP2::RenderPolice(), and SP2::Update().
void CReadFromText::ResetData (void)
Definition at line 38 of file ReadFromText.cpp.
References my_list.
Referenced by ReadTextFile(), ReadTextFileItem(), ReadTextFilePolice(), and ~CReadFromText().
int CReadFromText::ReturnListSize (void)
Definition at line 201 of file ReadFromText.cpp.
References item_list.
Referenced by SP2::CheckItem(), SP2::Init(), SP2::NPCShop(), SP2::RenderFNB(), SP2::RenderPolice(), SP2::UIupdates(), and SP2::Update().
int CReadFromText::ReturnReadListSize (void)
Definition at line 206 of file ReadFromText.cpp.
References my_list.
Field Documentation
vector<CItem* > CReadFromText::item_list private
Definition at line 28 of file ReadFromText.h.
Referenced by GetRenderPosItem(), ReadTextFileItem(), and ReturnListSize().
vector<CRenderPos*> CReadFromText::my_list private
Definition at line 27 of file ReadFromText.h.
Referenced by CReadFromText(), GetRenderPos(), ReadTextFile(), ResetData(), and ReturnReadListSize().
vector<CItem* > CReadFromText::Police_list private
Definition at line 29 of file ReadFromText.h.
Referenced by GetRenderPosPolice(), ReadTextFilePolice(), and ReadTextFilePoliceSize().
The documentation for this class was generated from the following files:
MyGraphics/Source/ReadFromText.h
MyGraphics/Source/ReadFromText.cpp