My Application: Camera3 Class Reference
Camera3 Class Reference
#include <Camera3.h>
Public Member Functions
Camera3 ()
~Camera3 ()
virtual void Init (const Vector3 &pos, const Vector3 &target, const Vector3 &up)
virtual void Update (double dt)
bool Limit (Vector3 &pos, Vector3 &target, int Border, float camSpeed)
void Doorsensor (Vector3 &pos, float camSpeed)
void Shuttersensor (Vector3 &pos, float camSpeed)
void StaffDoorsensor (Vector3 &pos, float camSpeed)
virtual void Reset ()
void setStaminaDupe (int stam)
int getStaminaDupe (void)
void setCameraState (int State)
int getCameraState (void)
Public Member Functions inherited from Camera
Camera ()
~Camera ()
Data Fields
Vector3 defaultPosition
Vector3 defaultTarget
Vector3 defaultUp
CCharacter player
bool EntranceDoor
bool ExitDoor
bool ShutterDoor
bool RightStaffDoor
bool LeftStaffDoor
bool moving
bool CameraMode
bool TrolleyMode
bool fixCamera
bool fixTranslation
bool isCollide
int CameraLock
float CamRotation
float CamRotationX
float CamRotationY
float CAMERA_SPEED
float TrolleyStateR
float TrolleyStateT
bool RepeatPress
int State
Application test
Data Fields inherited from Camera
Vector3 position
Vector3 target
Vector3 up
Private Attributes
int staminaDupe
int cameraState
Detailed Description
Definition at line 21 of file Camera3.h.
Constructor & Destructor Documentation
Camera3::Camera3 ()
Definition at line 14 of file Camera3.cpp.
References CAMERA_SPEED, CameraLock, CameraMode, cameraState, CamRotation, CamRotationX, CamRotationY, isCollide, RepeatPress, State, and TrolleyMode.
Camera3::~Camera3 ()
Definition at line 29 of file Camera3.cpp.
Member Function Documentation
void Camera3::Doorsensor (Vector3 & pos, float camSpeed)
Definition at line 125 of file Camera3.cpp.
References EntranceDoor, ExitDoor, Camera::position, Vector3::x, and Vector3::z.
Referenced by Update().
int Camera3::getCameraState (void)
Definition at line 537 of file Camera3.cpp.
References cameraState.
Referenced by SP2::Render(), Update(), and SP2::Update().
int Camera3::getStaminaDupe (void)
Definition at line 152 of file Camera3.cpp.
References staminaDupe.
Referenced by SP2::RenderScreenUI().
void Camera3::Init (const Vector3 & pos, const Vector3 & target, const Vector3 & up) virtual
Reimplemented from Camera.
Definition at line 33 of file Camera3.cpp.
References Vector3::Cross(), defaultPosition, defaultTarget, defaultUp, Vector3::Normalize(), Vector3::Normalized(), Camera::position, Camera::target, and Vector3::y.
Referenced by SP2::Init().
bool Camera3::Limit (Vector3 & pos, Vector3 & target, int Border, float camSpeed)
Definition at line 44 of file Camera3.cpp.
References Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void Camera3::Reset () virtual
Reimplemented from Camera.
Definition at line 525 of file Camera3.cpp.
References defaultPosition, defaultTarget, defaultUp, Camera::position, Camera::target, and Camera::up.
void Camera3::setCameraState (int State)
Definition at line 532 of file Camera3.cpp.
References cameraState.
Referenced by SP2::Update().
void Camera3::setStaminaDupe (int stam)
Definition at line 147 of file Camera3.cpp.
References staminaDupe.
Referenced by Update().
void Camera3::Shuttersensor (Vector3 & pos, float camSpeed)
Definition at line 112 of file Camera3.cpp.
References Camera::position, ShutterDoor, Vector3::x, and Vector3::z.
Referenced by Update().
void Camera3::StaffDoorsensor (Vector3 & pos, float camSpeed)
Definition at line 89 of file Camera3.cpp.
References LeftStaffDoor, Camera::position, RightStaffDoor, Vector3::x, and Vector3::z.
Referenced by Update().
void Camera3::Update (double dt) virtual
Reimplemented from Camera.
Definition at line 157 of file Camera3.cpp.
References CAMERA_SPEED, CameraLock, CameraMode, CamRotation, CamRotationX, CamRotationY, Vector3::Cross(), Doorsensor(), fixCamera, fixTranslation, getCameraState(), Application::getPosX(), Application::getPosY(), CCharacter::getStamina(), isCollide, Application::IsKeyPressed(), Application::IsKeyReleased(), Limit(), Application::mousePos(), moving, Vector3::Normalize(), Vector3::Normalized(), player, Camera::position, RepeatPress, CCharacter::setStamina(), setStaminaDupe(), Mtx44::SetToRotation(), Shuttersensor(), StaffDoorsensor(), State, Camera::target, test, TrolleyMode, TrolleyStateR, TrolleyStateT, Camera::up, Vector3::x, Vector3::y, and Vector3::z.
Referenced by SP2::Update().
Field Documentation
float Camera3::CAMERA_SPEED
Definition at line 66 of file Camera3.h.
Referenced by Camera3(), and Update().
int Camera3::CameraLock
Definition at line 62 of file Camera3.h.
Referenced by Camera3(), SP2::CharacterCrouch(), and Update().
bool Camera3::CameraMode
Definition at line 45 of file Camera3.h.
Referenced by Camera3(), Update(), and SP2::Update().
int Camera3::cameraState private
Definition at line 25 of file Camera3.h.
Referenced by Camera3(), getCameraState(), and setCameraState().
float Camera3::CamRotation
Definition at line 63 of file Camera3.h.
Referenced by Camera3(), SP2::RenderPlayer(), SP2::Trolley(), and Update().
float Camera3::CamRotationX
Definition at line 64 of file Camera3.h.
Referenced by Camera3(), SP2::RenderPlayer(), and Update().
float Camera3::CamRotationY
Definition at line 65 of file Camera3.h.
Referenced by Camera3(), SP2::RenderPlayer(), and Update().
Vector3 Camera3::defaultPosition
Definition at line 31 of file Camera3.h.
Referenced by Init(), and Reset().
Vector3 Camera3::defaultTarget
Definition at line 32 of file Camera3.h.
Referenced by Init(), and Reset().
Vector3 Camera3::defaultUp
Definition at line 33 of file Camera3.h.
Referenced by Init(), and Reset().
bool Camera3::EntranceDoor
Definition at line 39 of file Camera3.h.
Referenced by Doorsensor(), and SP2::DoorSlide().
bool Camera3::ExitDoor
Definition at line 40 of file Camera3.h.
Referenced by Doorsensor(), and SP2::DoorSlide().
bool Camera3::fixCamera
Definition at line 47 of file Camera3.h.
Referenced by Update().
bool Camera3::fixTranslation
Definition at line 48 of file Camera3.h.
Referenced by Update().
bool Camera3::isCollide
Definition at line 49 of file Camera3.h.
Referenced by SP2::BoundsCheck(), Camera3(), and Update().
bool Camera3::LeftStaffDoor
Definition at line 43 of file Camera3.h.
Referenced by SP2::DoorSlide(), and StaffDoorsensor().
bool Camera3::moving
Definition at line 44 of file Camera3.h.
Referenced by Update().
CCharacter Camera3::player
Definition at line 34 of file Camera3.h.
Referenced by Update().
bool Camera3::RepeatPress
Definition at line 69 of file Camera3.h.
Referenced by Camera3(), and Update().
bool Camera3::RightStaffDoor
Definition at line 42 of file Camera3.h.
Referenced by SP2::DoorSlide(), and StaffDoorsensor().
bool Camera3::ShutterDoor
Definition at line 41 of file Camera3.h.
Referenced by SP2::ShutterOpen(), and Shuttersensor().
int Camera3::staminaDupe private
Definition at line 24 of file Camera3.h.
Referenced by getStaminaDupe(), and setStaminaDupe().
int Camera3::State
Definition at line 70 of file Camera3.h.
Referenced by Camera3(), and Update().
Application Camera3::test
Definition at line 72 of file Camera3.h.
Referenced by Update().
bool Camera3::TrolleyMode
Definition at line 46 of file Camera3.h.
Referenced by Camera3(), SP2::Trolley(), and Update().
float Camera3::TrolleyStateR
Definition at line 67 of file Camera3.h.
Referenced by Update().
float Camera3::TrolleyStateT
Definition at line 68 of file Camera3.h.
Referenced by Update().
The documentation for this class was generated from the following files:
MyGraphics/Source/Camera3.h
MyGraphics/Source/Camera3.cpp