My Application: Application Class Reference
Application Class Reference
#include <Application.h>
Public Member Functions
Application ()
~Application ()
void Init ()
void Run ()
void Exit ()
void setPosX (double x)
void setPosY (double y)
double getPosX (void)
double getPosY (void)
void mousePos (void)
Static Public Member Functions
static bool IsKeyPressed (unsigned short key)
static bool IsKeyReleased (unsigned short key)
Data Fields
double DMX
double DMY
Private Attributes
StopWatch m_timer
double MX
double MY
Detailed Description
Definition at line 17 of file Application.h.
Constructor & Destructor Documentation
Application::Application ()
Definition at line 57 of file Application.cpp.
Application::~Application ()
Definition at line 61 of file Application.cpp.
Member Function Documentation
void Application::Exit ()
Definition at line 157 of file Application.cpp.
References m_window.
Referenced by main().
double Application::getPosX (void)
Definition at line 75 of file Application.cpp.
References MX.
Referenced by mousePos(), CCameraSecurity::Update(), and Camera3::Update().
double Application::getPosY (void)
Definition at line 80 of file Application.cpp.
References MY.
Referenced by mousePos(), CCameraSecurity::Update(), and Camera3::Update().
void Application::Init ()
Definition at line 85 of file Application.cpp.
References error_callback(), m_window, and resize_callback().
Referenced by main().
bool Application::IsKeyPressed (unsigned short key) static
Definition at line 47 of file Application.cpp.
Referenced by SP2::CharacterCrouch(), SP2::CheckItem(), SP2::CheckOut(), SP2::EscapeSteal(), SP2::RenderScreenUI(), Run(), SP2::Trolley(), Camera::Update(), Camera2::Update(), Camera3::Update(), and SP2::Update().
bool Application::IsKeyReleased (unsigned short key) static
Definition at line 52 of file Application.cpp.
Referenced by SP2::CharacterCrouch(), and Camera3::Update().
void Application::mousePos (void)
Definition at line 165 of file Application.cpp.
References DMX, DMY, getPosX(), getPosY(), m_window, setPosX(), and setPosY().
Referenced by CCameraSecurity::Update(), and Camera3::Update().
void Application::Run ()
Definition at line 135 of file Application.cpp.
References Scene::Exit(), frameTime, StopWatch::getElapsedTime(), Scene::Init(), IsKeyPressed(), m_timer, m_window, Scene::Render(), StopWatch::startTimer(), Scene::Update(), and StopWatch::waitUntil().
Referenced by main().
void Application::setPosX (double x)
Definition at line 65 of file Application.cpp.
References MX.
Referenced by mousePos().
void Application::setPosY (double y)
Definition at line 70 of file Application.cpp.
References MY.
Referenced by mousePos().
Field Documentation
double Application::DMX
Definition at line 32 of file Application.h.
Referenced by mousePos().
double Application::DMY
Definition at line 33 of file Application.h.
Referenced by mousePos().
StopWatch Application::m_timer private
Definition at line 40 of file Application.h.
Referenced by Run().
double Application::MX private
Definition at line 41 of file Application.h.
Referenced by getPosX(), and setPosX().
double Application::MY private
Definition at line 42 of file Application.h.
Referenced by getPosY(), and setPosY().
The documentation for this class was generated from the following files:
MyGraphics/Source/Application.h
MyGraphics/Source/Application.cpp