My Application: SP2 Class Reference
SP2 Class Reference
#include <SP2.h>
Public Member Functions
SP2 ()
~SP2 ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
CReadFromText data
CReadFromText shelve
CReadFromText cashier
CReadFromText fridge
CReadFromText character
CReadFromText cashiermodel
CReadFromText FNB
CReadFromText Police
CReadFromText PoliceCol
CReadFromText PoliceMan
CReadFromText Building01
CReadFromText Building02
CReadFromText Building03
CReadFromText Building04
CReadFromText Lamp
CReadFromText Locker
vector< CBullet * > bullet
vector< CBullet * > Policebullet
CBullet shoot
CBullet Trolleyz
vector< CCollisionBounds * > colBounds
vector< CCollisionBounds * > VanBounds
vector< CCollisionBounds * > LockerBounds
CNPC npc
CNPC guard
CNPC shopper
CNPC shopperTwo
CNPC patroler
CCharacter player
CTrolley trolley
CPolice police1
CPolice police2
CPolice police3
CPolice police4
CPolice Escape
bool police
int Lightswitch
bool CheckoutActive
float EscapeCarMove
bool EscapeEnd
float ExplosionScale
int MenuState
float MenuLimit
float GunOffset
float GunSwing
float DupeRot
float DupeRotArms
float DupeRotArmsY
Csounds MusicPlayer
int RandomItem
Private Types
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_TYPE, U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC,
U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT1_POSITION,
U_LIGHT1_TYPE, U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT1_KC,
U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_COSCUTOFF,
U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT2_POSITION, U_LIGHT2_TYPE,
U_LIGHT2_COLOR, U_LIGHT2_POWER, U_LIGHT2_KC, U_LIGHT2_KL,
U_LIGHT2_KQ, U_LIGHT2_SPOTDIRECTION, U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER,
U_LIGHT2_EXPONENT, U_LIGHT3_POSITION, U_LIGHT3_TYPE, U_LIGHT3_COLOR,
U_LIGHT3_POWER, U_LIGHT3_KC, U_LIGHT3_KL, U_LIGHT3_KQ,
U_LIGHT3_SPOTDIRECTION, U_LIGHT3_COSCUTOFF, U_LIGHT3_COSINNER, U_LIGHT3_EXPONENT,
U_LIGHT4_POSITION, U_LIGHT4_TYPE, U_LIGHT4_COLOR, U_LIGHT4_POWER,
U_LIGHT4_KC, U_LIGHT4_KL, U_LIGHT4_KQ, U_LIGHT4_SPOTDIRECTION,
U_LIGHT4_COSCUTOFF, U_LIGHT4_COSINNER, U_LIGHT4_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
enum GEOMETRY_TYPE {
GEO_AXES, GEO_QUAD, GEO_LIGHTBALL, GEO_LIGHTBALL2,
GEO_CYLINDER, GEO_MODEL1, GEO_MODEL_HEAD, GEO_MODEL_BODY,
GEO_MODEL_LEFTARM, GEO_MODEL_RIGHTARM, GEO_MODEL_LEFTLEG, GEO_MODEL_RIGHTLEG,
GEO_MODEL_SHOPPER2_HEAD, GEO_MODEL_SHOPPER2_BODY, GEO_MODEL_SHOPPER2_LEFTARM, GEO_MODEL_SHOPPER2_RIGHTARM,
GEO_MODEL_SHOPPER2_LEFTLEG, GEO_MODEL_SHOPPER2_RIGHTLEG, GEO_MODEL_CASHIER_HEAD, GEO_MODEL_CASHIER_BODY,
GEO_MODEL_CASHIER_LEFTARM, GEO_MODEL_CASHIER_RIGHTARM, GEO_MODEL_CASHIER_LEFTLEG, GEO_MODEL_CASHIER_RIGHTLEG,
GEO_MODEL_GUARD_HEAD, GEO_MODEL_GUARD_BODY, GEO_MODEL_GUARD_LEFTARM, GEO_MODEL_GUARD_RIGHTARM,
GEO_MODEL_GUARD_LEFTLEG, GEO_MODEL_GUARD_RIGHTLEG, GEO_MODEL_DOORMAN, GEO_MODEL_MART,
GEO_MODEL_DOOR, GEO_MODEL_FLOOR, GEO_MODEL_CASHIER, GEO_MODEL_CHAR1,
GEO_MODEL_FRIDGE, GEO_MODEL_SHELF, GEO_MODEL_CEREAL_1, GEO_MODEL_CEREAL_2,
GEO_MODEL_CEREAL_3, GEO_MODEL_WATERCAN, GEO_MODEL_MTDEW, GEO_MODEL_COKE,
GEO_MODEL_PEPSI, GEO_MODEL_HERSHEY, GEO_MODEL_ROCHER, GEO_MODEL_BBCAN,
GEO_MODEL_PUMPKINCAN, GEO_MODEL_TOMATOSOUPCAN, GEO_MODEL_PEASNCARROTCAN, GEO_MODEL_LAYSCHIPS,
GEO_MODEL_PIZZA, GEO_MODEL_ICECREAM, GEO_MODEL_MCNCHEESE, GEO_MODEL_SARDINES,
GEO_MODEL_AYAMCAN, GEO_MODEL_CHICKENSTOCK, GEO_MODEL_TOBLERONE, GEO_MODEL_VEGCAN,
GEO_MODEL_MILO, GEO_MODEL_SARDCAN, GEO_MODEL_CACTUS, GEO_MODEL_REDITOS,
GEO_MODEL_DEWITOS, GEO_MODEL_DIABETOS, GEO_MODEL_MOATIES, GEO_MODEL_SWBOX,
GEO_MODEL_DOSH, GEO_MODEL_PISTOL, GEO_MODEL_RIFLE, GEO_MODEL_SUPPLIES,
GEO_MODEL_SFFOOD, GEO_MODEL_SCHIPS, GEO_MODEL_SCANS, GEO_MODEL_SCVEG,
GEO_MODEL_SCEREAL, GEO_MODEL_SGUNS, GEO_MODEL_STFOOD, GEO_TEXT,
GEO_XHAIR, GEO_HP, GEO_STAM, GEO_HPI,
GEO_STAMI, GEO_ALERT, GEO_UI, GEO_DIALOGUEBOX,
GEO_MODEL_CAMERA, GEO_MODEL_STAFFDOOR, GEO_MODEL_SHUTTER, GEO_MODEL_ROAD,
GEO_MODEL_FENCE, GEO_MODEL_BOARD1, GEO_MODEL_BOARD2, GEO_MODEL_BOARD3,
GEO_MODEL_BOARD4, GEO_MODEL_LIGHTS, GEO_MODEL_GUARDHOUSE, GEO_MODEL_GUARDCONTROL,
GEO_MODEL_TROLLEY, GEO_MENUBOX, GEO_MENUSELECT, GEO_PLAYER_ARMSL,
GEO_PLAYER_ARMSR, GEO_MODEL_BULLET, GEO_MODEL_POLICEVAN, GEO_MODEL_POLICEVANWHEEL,
GEO_MODEL_POLICEMAN, GEO_MODEL_POLICEMAN_DAMAGED, GEO_MODEL_BROKEN, GEO_EXPLODE,
GEO_STARTBTN, GEO_INSTRUCTIONBTN, GEO_ACHIEVEBTN, GEO_EXITBTN,
GEO_LOGO, GEO_TINT, GEO_ENDSCREEN, GEO_WINSCREEN,
GEO_ACHIEVESCREEN, GEO_INSTRUCTIONSSCREEN, GEO_MODEL_ESCAPE, GEO_MAIN_INSTRUCT,
GEO_PINSTRUCTBOX, GEO_SINSTRUCTBOX, GEO_BUILDING01, GEO_BUILDING02,
GEO_BUILDING03, GEO_BUILDING04, GEO_LAMP, GEO_FLAG,
GEO_MISSINGITEM, GEO_LOCKER, GEO_LEFT, GEO_RIGHT,
GEO_TOP, GEO_BOTTOM, GEO_FRONT, GEO_BACK,
NUM_GEOMETRY
}
Private Member Functions
void EscapeSteal ()
void RenderWorld ()
void RenderSkybox ()
void RenderCashier ()
void RenderCashierModel ()
void RenderFridge ()
void RenderShelves ()
void RenderCharacter ()
void RenderFNB ()
void RenderPlayer ()
void RenderScreenUI ()
void RenderItemMissing ()
void RenderAnimate ()
void RenderAnimate2 ()
void RenderAnimateGuard ()
void RenderPolice ()
void PoliceShoot (double dt)
void RenderBuilding ()
void ItemMissing ()
void SetPrevPos (void)
void RenderMesh (Mesh *mesh, bool enableLight)
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
void RenderUI (Mesh *mesh, Color color, float sizeX, float sizeY, float sizeZ, float x, float y)
void CheckItem ()
void CharacterCrouch ()
void DoorSlide ()
void ShutterOpen ()
void BoundsCheck ()
void BoundsCheckTrolley (float x, float y, float z)
void UIupdates (double dt)
void Animate (double dt)
void CheckOut ()
void NPCwalk ()
void UnpaidItems ()
void Stealing ()
void RenderBasicModel ()
void Trolley ()
void TrolleyUpdate ()
void NPCShop ()
bool BulletCollision (float x, float y, float z, double dt)
bool BulletCollisionEnemy (float x, float y, float z)
void MainMenu ()
void MenuUpdate (double dt)
void LightsReset ()
Private Attributes
unsigned m_vertexArrayID
Mesh * meshList [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
float rotateAngle
float FPS
float angle
float translate
float translateY
bool walk
bool playeridle
bool NPC1idle
bool NPC2idle
bool NPC3idle
bool paying
bool paid
bool ShopStaff
bool GameEndStaff
bool GameEndSteal
bool GameEndStealLose
double DTimer
string DTtime
bool UpdateItemMissing
string missinglist
string nameofitem [10]
int noofitem [10]
float CashierOffetX
float CashierOffetY
float CashierOffetZ
float PoliceInstructTimer
float StaffInstructTimer
bool PInstruct
bool SInstruct
bool Instruct
std::string FPS_count
std::string XPos
std::string ZPos
std::string Target
std::string HP
std::string STAM
std::string MONEY
std::string ROLE
std::string INSTRUCTIONS1
std::string INSTRUCTIONS2
std::string INSTRUCTIONS3
std::string INSTRUCTIONS4
std::string TITLE
std::string ItemName
std::string BulletCount
std::string ItemPrice
std::string TheifTut
std::string ShopTut
std::string GuardTut
std::string EndGame
std::string EndGameSteal
std::string EndGameStealL
float EntranceDoorSlide
float ExitDoorSlide
float ShutterDoorOpen
float RightStaffDoorSlide
float LeftStaffDoorSlide
float ArmSwing
bool MenuKey
float LengthY
Camera3 camera
CCameraSecurity EndScene
CCameraSecurity Security1
CCameraSecurity Security2
Camera3 cameraDupe
MS modelStack
MS viewStack
MS projectionStack
Light lights [10]
Detailed Description
Definition at line 30 of file SP2.h.
Member Enumeration Documentation
enum SP2::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_QUAD
GEO_LIGHTBALL
GEO_LIGHTBALL2
GEO_CYLINDER
GEO_MODEL1
GEO_MODEL_HEAD
GEO_MODEL_BODY
GEO_MODEL_LEFTARM
GEO_MODEL_RIGHTARM
GEO_MODEL_LEFTLEG
GEO_MODEL_RIGHTLEG
GEO_MODEL_SHOPPER2_HEAD
GEO_MODEL_SHOPPER2_BODY
GEO_MODEL_SHOPPER2_LEFTARM
GEO_MODEL_SHOPPER2_RIGHTARM
GEO_MODEL_SHOPPER2_LEFTLEG
GEO_MODEL_SHOPPER2_RIGHTLEG
GEO_MODEL_CASHIER_HEAD
GEO_MODEL_CASHIER_BODY
GEO_MODEL_CASHIER_LEFTARM
GEO_MODEL_CASHIER_RIGHTARM
GEO_MODEL_CASHIER_LEFTLEG
GEO_MODEL_CASHIER_RIGHTLEG
GEO_MODEL_GUARD_HEAD
GEO_MODEL_GUARD_BODY
GEO_MODEL_GUARD_LEFTARM
GEO_MODEL_GUARD_RIGHTARM
GEO_MODEL_GUARD_LEFTLEG
GEO_MODEL_GUARD_RIGHTLEG
GEO_MODEL_DOORMAN
GEO_MODEL_MART
GEO_MODEL_DOOR
GEO_MODEL_FLOOR
GEO_MODEL_CASHIER
GEO_MODEL_CHAR1
GEO_MODEL_FRIDGE
GEO_MODEL_SHELF
GEO_MODEL_CEREAL_1
GEO_MODEL_CEREAL_2
GEO_MODEL_CEREAL_3
GEO_MODEL_WATERCAN
GEO_MODEL_MTDEW
GEO_MODEL_COKE
GEO_MODEL_PEPSI
GEO_MODEL_HERSHEY
GEO_MODEL_ROCHER
GEO_MODEL_BBCAN
GEO_MODEL_PUMPKINCAN
GEO_MODEL_TOMATOSOUPCAN
GEO_MODEL_PEASNCARROTCAN
GEO_MODEL_LAYSCHIPS
GEO_MODEL_PIZZA
GEO_MODEL_ICECREAM
GEO_MODEL_MCNCHEESE
GEO_MODEL_SARDINES
GEO_MODEL_AYAMCAN
GEO_MODEL_CHICKENSTOCK
GEO_MODEL_TOBLERONE
GEO_MODEL_VEGCAN
GEO_MODEL_MILO
GEO_MODEL_SARDCAN
GEO_MODEL_CACTUS
GEO_MODEL_REDITOS
GEO_MODEL_DEWITOS
GEO_MODEL_DIABETOS
GEO_MODEL_MOATIES
GEO_MODEL_SWBOX
GEO_MODEL_DOSH
GEO_MODEL_PISTOL
GEO_MODEL_RIFLE
GEO_MODEL_SUPPLIES
GEO_MODEL_SFFOOD
GEO_MODEL_SCHIPS
GEO_MODEL_SCANS
GEO_MODEL_SCVEG
GEO_MODEL_SCEREAL
GEO_MODEL_SGUNS
GEO_MODEL_STFOOD
GEO_TEXT
GEO_XHAIR
GEO_HP
GEO_STAM
GEO_HPI
GEO_STAMI
GEO_ALERT
GEO_UI
GEO_DIALOGUEBOX
GEO_MODEL_CAMERA
GEO_MODEL_STAFFDOOR
GEO_MODEL_SHUTTER
GEO_MODEL_ROAD
GEO_MODEL_FENCE
GEO_MODEL_BOARD1
GEO_MODEL_BOARD2
GEO_MODEL_BOARD3
GEO_MODEL_BOARD4
GEO_MODEL_LIGHTS
GEO_MODEL_GUARDHOUSE
GEO_MODEL_GUARDCONTROL
GEO_MODEL_TROLLEY
GEO_MENUBOX
GEO_MENUSELECT
GEO_PLAYER_ARMSL
GEO_PLAYER_ARMSR
GEO_MODEL_BULLET
GEO_MODEL_POLICEVAN
GEO_MODEL_POLICEVANWHEEL
GEO_MODEL_POLICEMAN
GEO_MODEL_POLICEMAN_DAMAGED
GEO_MODEL_BROKEN
GEO_EXPLODE
GEO_STARTBTN
GEO_INSTRUCTIONBTN
GEO_ACHIEVEBTN
GEO_EXITBTN
GEO_LOGO
GEO_TINT
GEO_ENDSCREEN
GEO_WINSCREEN
GEO_ACHIEVESCREEN
GEO_INSTRUCTIONSSCREEN
GEO_MODEL_ESCAPE
GEO_MAIN_INSTRUCT
GEO_PINSTRUCTBOX
GEO_SINSTRUCTBOX
GEO_BUILDING01
GEO_BUILDING02
GEO_BUILDING03
GEO_BUILDING04
GEO_LAMP
GEO_FLAG
GEO_MISSINGITEM
GEO_LOCKER
GEO_LEFT
GEO_RIGHT
GEO_TOP
GEO_BOTTOM
GEO_FRONT
GEO_BACK
NUM_GEOMETRY
Definition at line 114 of file SP2.h.
enum SP2::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_TYPE
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_LIGHT1_POSITION
U_LIGHT1_TYPE
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_LIGHT2_POSITION
U_LIGHT2_TYPE
U_LIGHT2_COLOR
U_LIGHT2_POWER
U_LIGHT2_KC
U_LIGHT2_KL
U_LIGHT2_KQ
U_LIGHT2_SPOTDIRECTION
U_LIGHT2_COSCUTOFF
U_LIGHT2_COSINNER
U_LIGHT2_EXPONENT
U_LIGHT3_POSITION
U_LIGHT3_TYPE
U_LIGHT3_COLOR
U_LIGHT3_POWER
U_LIGHT3_KC
U_LIGHT3_KL
U_LIGHT3_KQ
U_LIGHT3_SPOTDIRECTION
U_LIGHT3_COSCUTOFF
U_LIGHT3_COSINNER
U_LIGHT3_EXPONENT
U_LIGHT4_POSITION
U_LIGHT4_TYPE
U_LIGHT4_COLOR
U_LIGHT4_POWER
U_LIGHT4_KC
U_LIGHT4_KL
U_LIGHT4_KQ
U_LIGHT4_SPOTDIRECTION
U_LIGHT4_COSCUTOFF
U_LIGHT4_COSINNER
U_LIGHT4_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 33 of file SP2.h.
Constructor & Destructor Documentation
SP2::SP2 ()
Definition at line 16 of file SP2.cpp.
References Lightswitch.
SP2::~SP2 ()
Definition at line 21 of file SP2.cpp.
Member Function Documentation
void SP2::Animate (double dt) private
Definition at line 1384 of file SP2.cpp.
References angle, translate, translateY, walk, and WSPEED.
Referenced by Update().
void SP2::BoundsCheck () private
Definition at line 1438 of file SP2.cpp.
References camera, cameraDupe, cashier, cashiermodel, data, fridge, CNPC::getPosX(), CNPC::getPosZ(), CReadFromText::GetRenderPos(), CRenderPos::getTranslationX(), CRenderPos::getTranslationZ(), guard, Camera3::isCollide, CTrolley::LastXMove, CTrolley::LastZMove, LockerBounds, NPC1idle, NPC2idle, NPC3idle, patroler, player, playeridle, police, Camera::position, shelve, shopper, shopperTwo, Camera::target, CCharacter::trolley, trolley, VanBounds, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void SP2::BoundsCheckTrolley (float x, float y, float z) private
Definition at line 1861 of file SP2.cpp.
References camera, cameraDupe, cashier, cashiermodel, data, fridge, CNPC::getPosX(), CNPC::getPosZ(), CReadFromText::GetRenderPos(), CRenderPos::getTranslationX(), CRenderPos::getTranslationZ(), Camera3::isCollide, patroler, playeridle, police, Camera::position, shelve, shopper, Camera::target, VanBounds, Vector3::x, and Vector3::z.
Referenced by Update().
bool SP2::BulletCollision (float x, float y, float z, double dt) private
Definition at line 4208 of file SP2.cpp.
References cashier, colBounds, CItem::Damaged, data, fridge, CItem::getItemName(), CReadFromText::GetRenderPos(), CReadFromText::GetRenderPosItem(), CReadFromText::GetRenderPosPolice(), CRenderPos::getTranslationX(), CRenderPos::getTranslationZ(), Police, PoliceMan, CItem::sethealth(), CItem::setItemAvailable(), shelve, Vector3::x, and Vector3::z.
Referenced by Update().
bool SP2::BulletCollisionEnemy (float x, float y, float z) private
Definition at line 4392 of file SP2.cpp.
References cashier, data, fridge, CItem::getItemName(), CReadFromText::GetRenderPos(), CReadFromText::GetRenderPosItem(), CRenderPos::getTranslationX(), CRenderPos::getTranslationZ(), player, Police, PoliceCol, CCharacter::setHealth(), CItem::setItemAvailable(), shelve, VanBounds, Vector3::x, and Vector3::z.
Referenced by Update().
void SP2::CharacterCrouch () private
Definition at line 1422 of file SP2.cpp.
References camera, Camera3::CameraLock, Camera3::CamRotationY, Application::IsKeyPressed(), Application::IsKeyReleased(), Camera::position, Camera::target, and Vector3::y.
Referenced by Update().
void SP2::CheckItem () private
Definition at line 3329 of file SP2.cpp.
References ArmSwing, camera, CBullet::clip, CCharacter::dropItem(), FNB, CCharacter::getInventory(), CCharacter::getInventoryCap(), CItem::getItemAvailability(), CItem::getItemName(), CItem::getItemPrice(), CItem::getItemTranslationX(), CItem::getItemTranslationY(), CItem::getItemTranslationZ(), CReadFromText::GetRenderPosItem(), Application::IsKeyPressed(), ItemName, player, CCharacter::returnInvenSize(), CReadFromText::ReturnListSize(), CCharacter::setInventory(), CItem::setItemAvailable(), shoot, CCharacter::Takeitems, Camera::target, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void SP2::CheckOut () private
Definition at line 3403 of file SP2.cpp.
References ArmSwing, camera, cashier, CashierOffetX, CashierOffetY, CashierOffetZ, Csounds::CheckOut(), GEO_MODEL_CACTUS, GEO_MODEL_CEREAL_2, GEO_MODEL_CHICKENSTOCK, GEO_MODEL_COKE, GEO_MODEL_DEWITOS, GEO_MODEL_ICECREAM, GEO_MODEL_LAYSCHIPS, GEO_MODEL_MCNCHEESE, GEO_MODEL_MILO, GEO_MODEL_MOATIES, GEO_MODEL_MTDEW, GEO_MODEL_PEPSI, GEO_MODEL_PIZZA, GEO_MODEL_PUMPKINCAN, GEO_MODEL_REDITOS, GEO_MODEL_ROCHER, GEO_MODEL_SARDCAN, GEO_MODEL_TOBLERONE, GEO_MODEL_TOMATOSOUPCAN, GEO_MODEL_VEGCAN, CCharacter::getInventory(), CItem::getItemName(), CItem::getItemPrice(), CReadFromText::GetRenderPos(), CRenderPos::getTranslationX(), CRenderPos::getTranslationY(), CRenderPos::getTranslationZ(), Application::IsKeyPressed(), meshList, modelStack, MusicPlayer, paying, player, police, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), CCharacter::returnInvenSize(), CCharacter::sellItems(), CCharacter::setMoney(), ShopStaff, Camera::target, MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2::DoorSlide () private
Definition at line 2184 of file SP2.cpp.
References camera, CNPC::enterMart, Camera3::EntranceDoor, EntranceDoorSlide, Camera3::ExitDoor, ExitDoorSlide, CNPC::exitMart, Camera3::LeftStaffDoor, LeftStaffDoorSlide, Camera3::RightStaffDoor, RightStaffDoorSlide, and shopper.
Referenced by Update().
void SP2::EscapeSteal () private
Definition at line 3726 of file SP2.cpp.
References camera, EscapeEnd, Csounds::Explosion(), CCharacter::getInventory(), CItem::getItemPrice(), CCharacter::getMoney(), Application::IsKeyPressed(), MusicPlayer, player, police, CCharacter::returnInvenSize(), CCharacter::sellItems(), Camera3::setCameraState(), CCharacter::setMoney(), Camera::target, VanBounds, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2::Exit () virtual
Implements Scene.
Definition at line 5740 of file SP2.cpp.
References m_programID, m_vertexArrayID, meshList, MusicPlayer, NUM_GEOMETRY, and Csounds::~Csounds().
void SP2::Init () virtual
Implements Scene.
Definition at line 25 of file SP2.cpp.
References angle, ArmSwing, Building01, Building02, Building03, Building04, camera, cashier, cashiermodel, character, colBounds, Light::color, Light::cosCutoff, Light::cosInner, data, Math::DegreeToRadian(), DupeRot, DupeRotArms, DupeRotArmsY, EndScene, EntranceDoorSlide, EscapeCarMove, EscapeEnd, ExitDoorSlide, ExplosionScale, Light::exponent, FNB, fridge, GameEndStaff, GameEndSteal, GameEndStealLose, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateText(), GEO_ACHIEVEBTN, GEO_ACHIEVESCREEN, GEO_ALERT, GEO_AXES, GEO_BACK, GEO_BOTTOM, GEO_BUILDING01, GEO_BUILDING02, GEO_BUILDING03, GEO_BUILDING04, GEO_DIALOGUEBOX, GEO_ENDSCREEN, GEO_EXITBTN, GEO_EXPLODE, GEO_FLAG, GEO_FRONT, GEO_HP, GEO_HPI, GEO_INSTRUCTIONBTN, GEO_INSTRUCTIONSSCREEN, GEO_LAMP, GEO_LEFT, GEO_LIGHTBALL, GEO_LIGHTBALL2, GEO_LOCKER, GEO_LOGO, GEO_MAIN_INSTRUCT, GEO_MENUBOX, GEO_MENUSELECT, GEO_MISSINGITEM, GEO_MODEL_AYAMCAN, GEO_MODEL_BBCAN, GEO_MODEL_BOARD1, GEO_MODEL_BOARD2, GEO_MODEL_BOARD3, GEO_MODEL_BOARD4, GEO_MODEL_BODY, GEO_MODEL_BROKEN, GEO_MODEL_BULLET, GEO_MODEL_CACTUS, GEO_MODEL_CAMERA, GEO_MODEL_CASHIER, GEO_MODEL_CASHIER_BODY, GEO_MODEL_CASHIER_HEAD, GEO_MODEL_CASHIER_LEFTARM, GEO_MODEL_CASHIER_LEFTLEG, GEO_MODEL_CASHIER_RIGHTARM, GEO_MODEL_CASHIER_RIGHTLEG, GEO_MODEL_CEREAL_1, GEO_MODEL_CEREAL_2, GEO_MODEL_CEREAL_3, GEO_MODEL_CHAR1, GEO_MODEL_CHICKENSTOCK, GEO_MODEL_COKE, GEO_MODEL_DEWITOS, GEO_MODEL_DIABETOS, GEO_MODEL_DOOR, GEO_MODEL_DOORMAN, GEO_MODEL_DOSH, GEO_MODEL_ESCAPE, GEO_MODEL_FENCE, GEO_MODEL_FLOOR, GEO_MODEL_FRIDGE, GEO_MODEL_GUARD_BODY, GEO_MODEL_GUARD_HEAD, GEO_MODEL_GUARD_LEFTARM, GEO_MODEL_GUARD_LEFTLEG, GEO_MODEL_GUARD_RIGHTARM, GEO_MODEL_GUARD_RIGHTLEG, GEO_MODEL_GUARDCONTROL, GEO_MODEL_GUARDHOUSE, GEO_MODEL_HEAD, GEO_MODEL_HERSHEY, GEO_MODEL_ICECREAM, GEO_MODEL_LAYSCHIPS, GEO_MODEL_LEFTARM, GEO_MODEL_LEFTLEG, GEO_MODEL_LIGHTS, GEO_MODEL_MART, GEO_MODEL_MCNCHEESE, GEO_MODEL_MILO, GEO_MODEL_MOATIES, GEO_MODEL_MTDEW, GEO_MODEL_PEASNCARROTCAN, GEO_MODEL_PEPSI, GEO_MODEL_PISTOL, GEO_MODEL_PIZZA, GEO_MODEL_POLICEMAN, GEO_MODEL_POLICEMAN_DAMAGED, GEO_MODEL_POLICEVAN, GEO_MODEL_POLICEVANWHEEL, GEO_MODEL_PUMPKINCAN, GEO_MODEL_REDITOS, GEO_MODEL_RIFLE, GEO_MODEL_RIGHTARM, GEO_MODEL_RIGHTLEG, GEO_MODEL_ROAD, GEO_MODEL_ROCHER, GEO_MODEL_SARDCAN, GEO_MODEL_SARDINES, GEO_MODEL_SCANS, GEO_MODEL_SCEREAL, GEO_MODEL_SCHIPS, GEO_MODEL_SCVEG, GEO_MODEL_SFFOOD, GEO_MODEL_SGUNS, GEO_MODEL_SHELF, GEO_MODEL_SHOPPER2_BODY, GEO_MODEL_SHOPPER2_HEAD, GEO_MODEL_SHOPPER2_LEFTARM, GEO_MODEL_SHOPPER2_LEFTLEG, GEO_MODEL_SHOPPER2_RIGHTARM, GEO_MODEL_SHOPPER2_RIGHTLEG, GEO_MODEL_SHUTTER, GEO_MODEL_STAFFDOOR, GEO_MODEL_STFOOD, GEO_MODEL_SWBOX, GEO_MODEL_TOBLERONE, GEO_MODEL_TOMATOSOUPCAN, GEO_MODEL_TROLLEY, GEO_MODEL_VEGCAN, GEO_MODEL_WATERCAN, GEO_PINSTRUCTBOX, GEO_PLAYER_ARMSL, GEO_PLAYER_ARMSR, GEO_RIGHT, GEO_SINSTRUCTBOX, GEO_STAM, GEO_STAMI, GEO_STARTBTN, GEO_TEXT, GEO_TINT, GEO_TOP, GEO_UI, GEO_WINSCREEN, GEO_XHAIR, CItem::getItemAvailability(), CItem::getItemTranslationX(), CItem::getItemTranslationY(), CItem::getItemTranslationZ(), CRenderPos::getName(), CReadFromText::GetRenderPos(), CReadFromText::GetRenderPosItem(), CReadFromText::GetRenderPosPolice(), CRenderPos::getTranslationX(), CRenderPos::getTranslationY(), CRenderPos::getTranslationZ(), guard, GunOffset, GunSwing, CCameraSecurity::Init(), Camera3::Init(), Instruct, Light::kC, Light::kL, Light::kQ, Lamp, LeftStaffDoorSlide, LengthY, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, lights, MS::LoadMatrix(), LoadShaders(), LoadTGA(), Locker, LockerBounds, m_parameters, m_programID, m_vertexArrayID, Csounds::MainMusic(), MenuKey, MenuState, meshList, MusicPlayer, npc, NPC1idle, NPC2idle, NPC3idle, NUM_GEOMETRY, patroler, PInstruct, playeridle, Police, police, PoliceCol, PoliceMan, Light::position, Light::power, projectionStack, RandomItem, CReadFromText::ReadTextFile(), CReadFromText::ReadTextFileItem(), CNPC::ReadTextFilePath(), CReadFromText::ReadTextFilePolice(), CReadFromText::ReadTextFilePoliceSize(), CReadFromText::ReturnListSize(), CReadFromText::ReturnReadListSize(), RightStaffDoorSlide, ROLE, rotateAngle, Security1, Security2, Position::Set(), Color::Set(), Vector3::Set(), Camera3::setCameraState(), CCollisionBounds::SetCollisionBounds(), CNPC::setName(), CNPC::setPosX(), CNPC::setPosZ(), Mtx44::SetToPerspective(), shelve, shopper, shopperTwo, ShopStaff, ShutterDoorOpen, SInstruct, Light::spotDirection, Mesh::textureID, translate, translateY, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POSITION, U_LIGHT1_POWER, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_TYPE, U_LIGHT2_COLOR, U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER, U_LIGHT2_EXPONENT, U_LIGHT2_KC, U_LIGHT2_KL, U_LIGHT2_KQ, U_LIGHT2_POSITION, U_LIGHT2_POWER, U_LIGHT2_SPOTDIRECTION, U_LIGHT2_TYPE, U_LIGHT3_COLOR, U_LIGHT3_COSCUTOFF, U_LIGHT3_COSINNER, U_LIGHT3_EXPONENT, U_LIGHT3_KC, U_LIGHT3_KL, U_LIGHT3_KQ, U_LIGHT3_POSITION, U_LIGHT3_POWER, U_LIGHT3_SPOTDIRECTION, U_LIGHT3_TYPE, U_LIGHT4_COLOR, U_LIGHT4_COSCUTOFF, U_LIGHT4_COSINNER, U_LIGHT4_EXPONENT, U_LIGHT4_KC, U_LIGHT4_KL, U_LIGHT4_KQ, U_LIGHT4_POSITION, U_LIGHT4_POWER, U_LIGHT4_SPOTDIRECTION, U_LIGHT4_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, UpdateItemMissing, VanBounds, and walk.
void SP2::ItemMissing () private
Definition at line 3288 of file SP2.cpp.
References FNB, CItem::getItemAvailability(), CItem::getItemName(), CItem::getItemPrice(), CReadFromText::GetRenderPosItem(), missinglist, nameofitem, noofitem, player, RandomItem, CReadFromText::ReturnListSize(), CCharacter::setInventory(), and CItem::setItemAvailable().
Referenced by Update().
void SP2::LightsReset () private
Definition at line 3260 of file SP2.cpp.
References Light::color, lights, Lightswitch, m_parameters, police, Light::power, Color::Set(), U_LIGHT0_POWER, U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT2_COLOR, U_LIGHT2_POWER, U_LIGHT3_COLOR, U_LIGHT3_POWER, U_LIGHT4_COLOR, and U_LIGHT4_POWER.
Referenced by Update().
void SP2::MainMenu () private
Definition at line 3148 of file SP2.cpp.
References GEO_EXITBTN, GEO_INSTRUCTIONBTN, GEO_LOGO, GEO_STARTBTN, MenuKey, MenuState, meshList, and RenderUI().
Referenced by Render().
void SP2::MenuUpdate (double dt) private
Definition at line 3181 of file SP2.cpp.
References camera, Instruct, Application::IsKeyPressed(), lights, Lightswitch, m_parameters, MenuKey, MenuLimit, MenuState, Csounds::MetalClank(), MusicPlayer, Light::power, Camera3::setCameraState(), U_LIGHT0_POWER, U_LIGHT1_POWER, U_LIGHT2_POWER, U_LIGHT3_POWER, and U_LIGHT4_POWER.
Referenced by Update().
void SP2::NPCShop () private
Definition at line 5361 of file SP2.cpp.
References CNPC::cashIn, CNPC::Checkout(), CNPC::enterMart, FNB, CItem::getItemAvailability(), CItem::getItemName(), CNPC::getPosX(), CNPC::getPosZ(), CReadFromText::GetRenderPosItem(), CNPC::getRot(), CNPC::maxItem, playeridle, CNPC::respawn(), CReadFromText::ReturnListSize(), CItem::setItemAvailable(), CNPC::setShop(), shopper, and shopperTwo.
Referenced by Update().
void SP2::NPCwalk () private
Definition at line 1174 of file SP2.cpp.
References guard, npc, playeridle, CNPC::ShopPathing(), shopper, shopperTwo, and CNPC::TestAIPath().
Referenced by Update().
void SP2::PoliceShoot (double dt) private
Definition at line 4109 of file SP2.cpp.
References CPolice::arrived, CBullet::Direction, CItem::getItemAvailability(), CItem::getItemTranslationX(), CItem::getItemTranslationY(), CItem::getItemTranslationZ(), CReadFromText::GetRenderPosPolice(), police1, Policebullet, PoliceMan, CBullet::Position, CReadFromText::ReadTextFilePoliceSize(), and CItem::ShootCD.
Referenced by Update().
void SP2::Render () virtual
Implements Scene.
Definition at line 2612 of file SP2.cpp.
References bullet, camera, CheckOut(), DTtime, EndGame, EndGameSteal, EndGameStealL, EndScene, EscapeEnd, EscapeSteal(), ExplosionScale, GameEndStaff, GameEndSteal, GameEndStealLose, GEO_AXES, GEO_ENDSCREEN, GEO_EXPLODE, GEO_MODEL_BULLET, GEO_TEXT, GEO_WINSCREEN, Camera3::getCameraState(), Application::IsKeyPressed(), Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, lights, MS::LoadIdentity(), MS::LookAt(), m_parameters, MainMenu(), MenuKey, meshList, modelStack, player, police, Policebullet, MS::PopMatrix(), Light::position, Camera::position, CBullet::Position, MS::PushMatrix(), RenderFNB(), RenderItemMissing(), RenderMesh(), RenderPlayer(), RenderPolice(), RenderScreenUI(), RenderSkybox(), RenderTextOnScreen(), RenderUI(), RenderWorld(), CCharacter::returnInvenSize(), MS::Rotate(), MS::Scale(), Security1, Security2, ShopStaff, Light::spotDirection, Camera::target, MS::Top(), MS::Translate(), CCharacter::trolley, Trolley(), TrolleyUpdate(), Trolleyz, U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, U_LIGHT1_POSITION, U_LIGHT1_SPOTDIRECTION, U_LIGHT2_POSITION, U_LIGHT2_SPOTDIRECTION, U_LIGHT3_POSITION, U_LIGHT3_SPOTDIRECTION, U_LIGHT4_POSITION, U_LIGHT4_SPOTDIRECTION, Camera::up, UpdateItemMissing, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void SP2::RenderAnimate () private
Definition at line 5090 of file SP2.cpp.
References angle, GEO_MODEL_BODY, GEO_MODEL_HEAD, GEO_MODEL_LEFTARM, GEO_MODEL_LEFTLEG, GEO_MODEL_RIGHTARM, GEO_MODEL_RIGHTLEG, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Translate(), translate, and translateY.
Referenced by RenderCharacter().
void SP2::RenderAnimate2 () private
Definition at line 5123 of file SP2.cpp.
References angle, GEO_MODEL_SHOPPER2_BODY, GEO_MODEL_SHOPPER2_HEAD, GEO_MODEL_SHOPPER2_LEFTARM, GEO_MODEL_SHOPPER2_LEFTLEG, GEO_MODEL_SHOPPER2_RIGHTARM, GEO_MODEL_SHOPPER2_RIGHTLEG, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Translate(), translate, and translateY.
Referenced by RenderCharacter().
void SP2::RenderAnimateGuard () private
Definition at line 5057 of file SP2.cpp.
References angle, GEO_MODEL_GUARD_BODY, GEO_MODEL_GUARD_HEAD, GEO_MODEL_GUARD_LEFTARM, GEO_MODEL_GUARD_LEFTLEG, GEO_MODEL_GUARD_RIGHTARM, GEO_MODEL_GUARD_RIGHTLEG, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Translate(), translate, and translateY.
Referenced by RenderCharacter().
void SP2::RenderBasicModel () private
Definition at line 2789 of file SP2.cpp.
References GEO_MODEL_BODY, GEO_MODEL_HEAD, GEO_MODEL_LEFTARM, GEO_MODEL_LEFTLEG, GEO_MODEL_RIGHTARM, GEO_MODEL_RIGHTLEG, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), and MS::Translate().
void SP2::RenderBuilding () private
Definition at line 4955 of file SP2.cpp.
References Building01, Building02, Building03, Building04, GEO_BUILDING01, GEO_BUILDING02, GEO_BUILDING03, GEO_BUILDING04, GEO_FLAG, GEO_LAMP, GEO_LOCKER, CReadFromText::GetRenderPos(), CRenderPos::getRotation(), CRenderPos::getRX(), CRenderPos::getRY(), CRenderPos::getRZ(), CRenderPos::getScaleX(), CRenderPos::getScaleY(), CRenderPos::getScaleZ(), CRenderPos::getTranslationX(), CRenderPos::getTranslationY(), CRenderPos::getTranslationZ(), Lamp, Locker, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), CReadFromText::ReturnReadListSize(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderWorld().
void SP2::RenderCashier () private
Definition at line 4727 of file SP2.cpp.
References cashier, GEO_MODEL_CASHIER, CReadFromText::GetRenderPos(), CRenderPos::getRotation(), CRenderPos::getRX(), CRenderPos::getRY(), CRenderPos::getRZ(), CRenderPos::getScaleX(), CRenderPos::getScaleY(), CRenderPos::getScaleZ(), CRenderPos::getTranslationX(), CRenderPos::getTranslationY(), CRenderPos::getTranslationZ(), meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderWorld().
void SP2::RenderCashierModel () private
Definition at line 3814 of file SP2.cpp.
References cashiermodel, GEO_MODEL_CASHIER_BODY, GEO_MODEL_CASHIER_HEAD, GEO_MODEL_CASHIER_LEFTARM, GEO_MODEL_CASHIER_LEFTLEG, GEO_MODEL_CASHIER_RIGHTARM, GEO_MODEL_CASHIER_RIGHTLEG, CReadFromText::GetRenderPos(), CRenderPos::getRotation(), CRenderPos::getRX(), CRenderPos::getRY(), CRenderPos::getRZ(), CRenderPos::getScaleX(), CRenderPos::getScaleY(), CRenderPos::getScaleZ(), CRenderPos::getTranslationX(), CRenderPos::getTranslationY(), CRenderPos::getTranslationZ(), meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderCharacter().
void SP2::RenderCharacter () private
Definition at line 5026 of file SP2.cpp.
References character, CNPC::getPosX(), CNPC::getPosZ(), CReadFromText::GetRenderPos(), CNPC::getRot(), CRenderPos::getRX(), CRenderPos::getRY(), CRenderPos::getRZ(), CRenderPos::getScaleX(), CRenderPos::getScaleY(), CRenderPos::getScaleZ(), CRenderPos::getTranslationY(), guard, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderAnimate(), RenderAnimate2(), RenderAnimateGuard(), RenderCashierModel(), MS::Rotate(), MS::Scale(), shopper, shopperTwo, and MS::Translate().
Referenced by RenderWorld().
void SP2::RenderFNB () private
Definition at line 5258 of file SP2.cpp.
References FNB, GEO_MODEL_CACTUS, GEO_MODEL_CEREAL_2, GEO_MODEL_CHICKENSTOCK, GEO_MODEL_COKE, GEO_MODEL_DEWITOS, GEO_MODEL_ICECREAM, GEO_MODEL_LAYSCHIPS, GEO_MODEL_MCNCHEESE, GEO_MODEL_MILO, GEO_MODEL_MOATIES, GEO_MODEL_MTDEW, GEO_MODEL_PEPSI, GEO_MODEL_PISTOL, GEO_MODEL_PIZZA, GEO_MODEL_PUMPKINCAN, GEO_MODEL_REDITOS, GEO_MODEL_RIFLE, GEO_MODEL_ROCHER, GEO_MODEL_SARDCAN, GEO_MODEL_TOBLERONE, GEO_MODEL_TOMATOSOUPCAN, GEO_MODEL_VEGCAN, CItem::getItemAvailability(), CItem::getItemName(), CItem::getItemRotation(), CItem::getItemRX(), CItem::getItemRY(), CItem::getItemRZ(), CItem::getItemScaleX(), CItem::getItemScaleY(), CItem::getItemScaleZ(), CItem::getItemTranslationX(), CItem::getItemTranslationY(), CItem::getItemTranslationZ(), CReadFromText::GetRenderPosItem(), meshList, modelStack, police, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), CReadFromText::ReturnListSize(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SP2::RenderFridge () private
Definition at line 4740 of file SP2.cpp.
References fridge, GEO_MODEL_FRIDGE, CReadFromText::GetRenderPos(), CRenderPos::getRotation(), CRenderPos::getRX(), CRenderPos::getRY(), CRenderPos::getRZ(), CRenderPos::getScaleX(), CRenderPos::getScaleY(), CRenderPos::getScaleZ(), CRenderPos::getTranslationX(), CRenderPos::getTranslationY(), CRenderPos::getTranslationZ(), meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by RenderWorld().
void SP2::RenderItemMissing () private
Definition at line 2988 of file SP2.cpp.
References GEO_MISSINGITEM, GEO_TEXT, CCharacter::getInventory(), CItem::getItemName(), LengthY, meshList, player, RenderTextOnScreen(), RenderUI(), and CCharacter::returnInvenSize().
Referenced by Render().
void SP2::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 5597 of file SP2.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by CheckOut(), Render(), RenderAnimate(), RenderAnimate2(), RenderAnimateGuard(), RenderBasicModel(), RenderBuilding(), RenderCashier(), RenderCashierModel(), RenderFNB(), RenderFridge(), RenderPlayer(), RenderPolice(), RenderShelves(), RenderSkybox(), RenderUI(), RenderWorld(), Trolley(), and TrolleyUpdate().
void SP2::RenderPlayer () private
Definition at line 5156 of file SP2.cpp.
References ArmSwing, camera, Camera3::downSight, DupeRot, DupeRotArms, DupeRotArmsY, EscapeEnd, GEO_MODEL_RIFLE, GEO_PLAYER_ARMSR, GunOffset, GunSwing, meshList, modelStack, player, police, MS::PopMatrix(), Camera::position, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Translate(), CCharacter::trolley, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2::RenderPolice () private
Definition at line 3838 of file SP2.cpp.
References CPolice::arrived, CItem::Damaged, Escape, EscapeCarMove, GEO_MODEL_ESCAPE, GEO_MODEL_POLICEMAN, GEO_MODEL_POLICEMAN_DAMAGED, GEO_MODEL_POLICEVAN, GEO_MODEL_POLICEVANWHEEL, CItem::getItemAvailability(), CItem::getItemName(), CItem::getItemRotation(), CItem::getItemRX(), CItem::getItemRY(), CItem::getItemRZ(), CItem::getItemScaleX(), CItem::getItemScaleY(), CItem::getItemScaleZ(), CItem::getItemTranslationX(), CItem::getItemTranslationY(), CItem::getItemTranslationZ(), CReadFromText::GetRenderPosItem(), CReadFromText::GetRenderPosPolice(), meshList, modelStack, Police, police1, police2, police3, police4, PoliceMan, CPolice::PoliceRotate, CPolice::PoliceXMove, CPolice::PoliceZMove, MS::PopMatrix(), MS::PushMatrix(), CReadFromText::ReadTextFilePoliceSize(), RenderMesh(), CReadFromText::ReturnListSize(), MS::Rotate(), MS::Scale(), MS::Translate(), and CPolice::WheelRot.
Referenced by Render().
void SP2::RenderScreenUI () private
Definition at line 2808 of file SP2.cpp.
References BulletCount, camera, cashier, Camera3::downSight, FPS_count, GEO_DIALOGUEBOX, GEO_HP, GEO_HPI, GEO_MAIN_INSTRUCT, GEO_MODEL_CACTUS, GEO_MODEL_CEREAL_2, GEO_MODEL_CHICKENSTOCK, GEO_MODEL_COKE, GEO_MODEL_DEWITOS, GEO_MODEL_ICECREAM, GEO_MODEL_LAYSCHIPS, GEO_MODEL_MCNCHEESE, GEO_MODEL_MILO, GEO_MODEL_MOATIES, GEO_MODEL_MTDEW, GEO_MODEL_PEPSI, GEO_MODEL_PIZZA, GEO_MODEL_PUMPKINCAN, GEO_MODEL_REDITOS, GEO_MODEL_ROCHER, GEO_MODEL_SARDCAN, GEO_MODEL_TOBLERONE, GEO_MODEL_TOMATOSOUPCAN, GEO_MODEL_VEGCAN, GEO_PINSTRUCTBOX, GEO_SINSTRUCTBOX, GEO_STAM, GEO_STAMI, GEO_TEXT, GEO_UI, GEO_XHAIR, CCharacter::getHealth(), CCharacter::getInventory(), CCharacter::getInventoryCap(), CItem::getItemName(), CNPC::getPosX(), CNPC::getPosZ(), CReadFromText::GetRenderPos(), Camera3::getStaminaDupe(), CRenderPos::getTranslationX(), CRenderPos::getTranslationZ(), Instruct, INSTRUCTIONS1, INSTRUCTIONS2, INSTRUCTIONS3, INSTRUCTIONS4, ItemName, ItemPrice, meshList, MONEY, PInstruct, player, PoliceInstructTimer, Camera::position, RenderTextOnScreen(), RenderUI(), CCharacter::returnInvenSize(), ROLE, shopper, SInstruct, StaffInstructTimer, Vector3::x, and Vector3::z.
Referenced by Render().
void SP2::RenderShelves () private
Definition at line 4753 of file SP2.cpp.
References GEO_MODEL_SHELF, CReadFromText::GetRenderPos(), CRenderPos::getRotation(), CRenderPos::getRX(), CRenderPos::getRY(), CRenderPos::getRZ(), CRenderPos::getScaleX(), CRenderPos::getScaleY(), CRenderPos::getScaleZ(), CRenderPos::getTranslationX(), CRenderPos::getTranslationY(), CRenderPos::getTranslationZ(), meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), shelve, and MS::Translate().
Referenced by RenderWorld().
void SP2::RenderSkybox () private
Definition at line 3756 of file SP2.cpp.
References GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by Render().
void SP2::RenderText (Mesh * mesh, std::string text, Color color) private
Definition at line 5642 of file SP2.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void SP2::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 5669 of file SP2.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render(), RenderItemMissing(), and RenderScreenUI().
void SP2::RenderUI (Mesh * mesh, Color color, float sizeX, float sizeY, float sizeZ, float x, float y) private
Definition at line 5713 of file SP2.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Scale(), Mtx44::SetToOrtho(), Mesh::textureID, MS::Translate(), and viewStack.
Referenced by MainMenu(), Render(), RenderItemMissing(), and RenderScreenUI().
void SP2::RenderWorld () private
Definition at line 4783 of file SP2.cpp.
References data, EntranceDoorSlide, EscapeEnd, ExitDoorSlide, ExplosionScale, GEO_MODEL_BOARD1, GEO_MODEL_BOARD2, GEO_MODEL_BOARD3, GEO_MODEL_BOARD4, GEO_MODEL_BROKEN, GEO_MODEL_CAMERA, GEO_MODEL_DOOR, GEO_MODEL_FENCE, GEO_MODEL_FLOOR, GEO_MODEL_GUARDCONTROL, GEO_MODEL_GUARDHOUSE, GEO_MODEL_LIGHTS, GEO_MODEL_MART, GEO_MODEL_ROAD, GEO_MODEL_SHUTTER, GEO_MODEL_STAFFDOOR, CReadFromText::GetRenderPos(), CRenderPos::getRotation(), CRenderPos::getRX(), CRenderPos::getRY(), CRenderPos::getRZ(), CRenderPos::getScaleX(), CRenderPos::getScaleY(), CRenderPos::getScaleZ(), CRenderPos::getTranslationX(), CRenderPos::getTranslationY(), CRenderPos::getTranslationZ(), LeftStaffDoorSlide, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderBuilding(), RenderCashier(), RenderCharacter(), RenderFridge(), RenderMesh(), RenderShelves(), RightStaffDoorSlide, MS::Rotate(), MS::Scale(), ShutterDoorOpen, and MS::Translate().
Referenced by Render().
void SP2::SetPrevPos (void) private
Definition at line 1229 of file SP2.cpp.
References camera, cameraDupe, Camera::position, Camera::target, and Camera::up.
Referenced by Update().
void SP2::ShutterOpen () private
Definition at line 2169 of file SP2.cpp.
References camera, Camera3::ShutterDoor, and ShutterDoorOpen.
Referenced by Update().
void SP2::Stealing () private
Definition at line 1201 of file SP2.cpp.
References Light::color, lights, Lightswitch, m_parameters, police, Light::power, Color::Set(), U_LIGHT0_POWER, U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT2_COLOR, U_LIGHT2_POWER, U_LIGHT3_COLOR, U_LIGHT3_POWER, U_LIGHT4_COLOR, and U_LIGHT4_POWER.
Referenced by Update().
void SP2::Trolley () private
Definition at line 2243 of file SP2.cpp.
References camera, Camera3::CamRotation, data, CTrolley::DetectBulletPos, DupeRot, CTrolley::ExpansionSize, GEO_MODEL_TROLLEY, CReadFromText::GetRenderPos(), CRenderPos::getRotation(), CRenderPos::getRX(), CRenderPos::getRY(), CRenderPos::getRZ(), CRenderPos::getScaleX(), CRenderPos::getScaleY(), CRenderPos::getScaleZ(), CRenderPos::getTranslationX(), CRenderPos::getTranslationY(), CRenderPos::getTranslationZ(), Application::IsKeyPressed(), CTrolley::LastX, CTrolley::LastXMove, CTrolley::LastZ, CTrolley::LastZMove, meshList, modelStack, player, MS::PopMatrix(), Camera::position, CBullet::Position, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), CCharacter::setInventoryCap(), CTrolley::SetList(), Camera::target, MS::Translate(), CCharacter::trolley, trolley, CCharacter::trolleyDrop, Camera3::TrolleyMode, Trolleyz, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2::TrolleyUpdate () private
Definition at line 2305 of file SP2.cpp.
References data, GEO_MODEL_CACTUS, GEO_MODEL_CEREAL_2, GEO_MODEL_CHICKENSTOCK, GEO_MODEL_COKE, GEO_MODEL_DEWITOS, GEO_MODEL_ICECREAM, GEO_MODEL_LAYSCHIPS, GEO_MODEL_MCNCHEESE, GEO_MODEL_MILO, GEO_MODEL_MOATIES, GEO_MODEL_MTDEW, GEO_MODEL_PEPSI, GEO_MODEL_PIZZA, GEO_MODEL_PUMPKINCAN, GEO_MODEL_REDITOS, GEO_MODEL_ROCHER, GEO_MODEL_SARDCAN, GEO_MODEL_TOBLERONE, GEO_MODEL_TOMATOSOUPCAN, GEO_MODEL_VEGCAN, CCharacter::getInventory(), CItem::getItemName(), CReadFromText::GetRenderPos(), CRenderPos::getRX(), CRenderPos::getRY(), CRenderPos::getRZ(), CRenderPos::getScaleX(), CRenderPos::getScaleY(), CRenderPos::getScaleZ(), CRenderPos::getTranslationY(), CTrolley::LastRotation, CTrolley::LastX, CTrolley::LastZ, meshList, modelStack, player, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), CCharacter::returnInvenSize(), MS::Rotate(), MS::Scale(), MS::Translate(), CCharacter::trolley, trolley, and CCharacter::trolleyDrop.
Referenced by Render().
void SP2::UIupdates (double dt) private
Definition at line 1236 of file SP2.cpp.
References CBullet::bullet, BulletCount, camera, cashier, CBullet::clip, data, DTimer, DTtime, EndGame, EndGameSteal, EndGameStealL, FNB, FPS_count, GameEndStaff, CCharacter::getHealth(), CItem::getItemName(), CItem::getItemPrice(), CItem::getItemTranslationX(), CItem::getItemTranslationY(), CItem::getItemTranslationZ(), CCharacter::getMoney(), CReadFromText::GetRenderPos(), CReadFromText::GetRenderPosItem(), CCharacter::getStamina(), CRenderPos::getTranslationX(), CRenderPos::getTranslationY(), CRenderPos::getTranslationZ(), HP, ItemName, ItemPrice, CTrolley::LastX, CTrolley::LastZ, LockerBounds, MONEY, player, police, Camera::position, CReadFromText::ReturnListSize(), CBullet::RTime, shoot, ShopStaff, STAM, Camera::target, Target, CCharacter::trolley, trolley, VanBounds, Vector3::x, XPos, Vector3::y, Vector3::z, and ZPos.
Referenced by Update().
void SP2::UnpaidItems () private
Definition at line 1182 of file SP2.cpp.
References camera, player, police, Camera::position, CCharacter::returnInvenSize(), CCharacter::unpaiditems, and Vector3::z.
Referenced by Update().
void SP2::Update (double dt) virtual
Implements Scene.
Definition at line 802 of file SP2.cpp.
References Animate(), BoundsCheck(), BoundsCheckTrolley(), Csounds::Bullet(), CBullet::bullet, bullet, BulletCollision(), BulletCollisionEnemy(), camera, Camera3::CAMERA_SPEED, Camera3::CameraLock, Camera3::CameraMode, CharacterCrouch(), CheckItem(), CBullet::clip, CItem::Damaged, CItem::DamageReset, CBullet::Direction, DoorSlide(), Camera3::downSight, DupeRot, DupeRotArms, DupeRotArmsY, EscapeCarMove, EscapeEnd, ExplosionScale, GameEndSteal, GameEndStealLose, Camera3::getCameraState(), CCharacter::getHealth(), CItem::getItemAvailability(), CItem::getItemName(), CItem::getItemPrice(), CItem::getItemRotation(), CItem::getItemTranslationX(), CItem::getItemTranslationZ(), CReadFromText::GetRenderPosItem(), CReadFromText::GetRenderPosPolice(), GunOffset, GunSwing, Camera3::isCollide, Application::IsKeyPressed(), ItemMissing(), ItemName, LightsReset(), MS::LoadMatrix(), LockerBounds, MenuKey, MenuUpdate(), Camera3::MouseX, Camera3::MouseY, MusicPlayer, NPCShop(), NPCwalk(), PInstruct, player, Police, police, police1, police2, police3, police4, Policebullet, CPolice::PoliceDrive(), CPolice::PoliceDriveL(), PoliceInstructTimer, PoliceMan, PoliceShoot(), Camera::position, CBullet::Position, projectionStack, CReadFromText::ReadTextFilePoliceSize(), Csounds::Reload(), CItem::resethealth(), CItem::RespawnCD, CReadFromText::ReturnListSize(), ROLE, CBullet::RTime, Security1, Security2, Camera3::setCameraState(), CItem::setItemAvailable(), SetPrevPos(), Mtx44::SetToPerspective(), shoot, CBullet::ShootInterval, ShopStaff, ShutterOpen(), SInstruct, StaffInstructTimer, Stealing(), Camera::target, CCharacter::trolley, CCharacter::trolleyDrop, CBullet::TrolleyLimiter(), Trolleyz, UIupdates(), UnpaidItems(), CCameraSecurity::Update(), Camera3::Update(), Position::x, Vector3::x, Vector3::y, and Vector3::z.
Field Documentation
float SP2::angle private
Definition at line 344 of file SP2.h.
Referenced by Animate(), Init(), RenderAnimate(), RenderAnimate2(), and RenderAnimateGuard().
float SP2::ArmSwing private
Definition at line 400 of file SP2.h.
Referenced by CheckItem(), CheckOut(), Init(), and RenderPlayer().
CReadFromText SP2::Building01
Definition at line 288 of file SP2.h.
Referenced by Init(), and RenderBuilding().
CReadFromText SP2::Building02
Definition at line 289 of file SP2.h.
Referenced by Init(), and RenderBuilding().
CReadFromText SP2::Building03
Definition at line 290 of file SP2.h.
Referenced by Init(), and RenderBuilding().
CReadFromText SP2::Building04
Definition at line 291 of file SP2.h.
Referenced by Init(), and RenderBuilding().
vector<CBullet*> SP2::bullet
Definition at line 294 of file SP2.h.
Referenced by Render(), and Update().
std::string SP2::BulletCount private
Definition at line 386 of file SP2.h.
Referenced by RenderScreenUI(), and UIupdates().
Camera3 SP2::camera private
Definition at line 406 of file SP2.h.
Referenced by BoundsCheck(), BoundsCheckTrolley(), CharacterCrouch(), CheckItem(), CheckOut(), DoorSlide(), EscapeSteal(), Init(), MenuUpdate(), Render(), RenderPlayer(), RenderScreenUI(), SetPrevPos(), ShutterOpen(), Trolley(), UIupdates(), UnpaidItems(), and Update().
Camera3 SP2::cameraDupe private
Definition at line 410 of file SP2.h.
Referenced by BoundsCheck(), BoundsCheckTrolley(), and SetPrevPos().
CReadFromText SP2::cashier
Definition at line 280 of file SP2.h.
Referenced by BoundsCheck(), BoundsCheckTrolley(), BulletCollision(), BulletCollisionEnemy(), CheckOut(), Init(), RenderCashier(), RenderScreenUI(), and UIupdates().
CReadFromText SP2::cashiermodel
Definition at line 283 of file SP2.h.
Referenced by BoundsCheck(), BoundsCheckTrolley(), Init(), and RenderCashierModel().
float SP2::CashierOffetX private
Definition at line 364 of file SP2.h.
Referenced by CheckOut().
float SP2::CashierOffetY private
Definition at line 365 of file SP2.h.
Referenced by CheckOut().
float SP2::CashierOffetZ private
Definition at line 366 of file SP2.h.
Referenced by CheckOut().
CReadFromText SP2::character
Definition at line 282 of file SP2.h.
Referenced by Init(), and RenderCharacter().
bool SP2::CheckoutActive
Definition at line 322 of file SP2.h.
vector<CCollisionBounds*> SP2::colBounds
Definition at line 299 of file SP2.h.
Referenced by BulletCollision(), and Init().
CReadFromText SP2::data
Definition at line 278 of file SP2.h.
Referenced by BoundsCheck(), BoundsCheckTrolley(), BulletCollision(), BulletCollisionEnemy(), Init(), RenderWorld(), Trolley(), TrolleyUpdate(), and UIupdates().
double SP2::DTimer private
Definition at line 358 of file SP2.h.
Referenced by UIupdates().
string SP2::DTtime private
Definition at line 359 of file SP2.h.
Referenced by Render(), and UIupdates().
float SP2::DupeRot
Definition at line 330 of file SP2.h.
Referenced by Init(), RenderPlayer(), Trolley(), and Update().
float SP2::DupeRotArms
Definition at line 331 of file SP2.h.
Referenced by Init(), RenderPlayer(), and Update().
float SP2::DupeRotArmsY
Definition at line 332 of file SP2.h.
Referenced by Init(), RenderPlayer(), and Update().
std::string SP2::EndGame private
Definition at line 391 of file SP2.h.
Referenced by Render(), and UIupdates().
std::string SP2::EndGameSteal private
Definition at line 392 of file SP2.h.
Referenced by Render(), and UIupdates().
std::string SP2::EndGameStealL private
Definition at line 393 of file SP2.h.
Referenced by Render(), and UIupdates().
CCameraSecurity SP2::EndScene private
Definition at line 407 of file SP2.h.
Referenced by Init(), and Render().
float SP2::EntranceDoorSlide private
Definition at line 395 of file SP2.h.
Referenced by DoorSlide(), Init(), and RenderWorld().
CPolice SP2::Escape
Definition at line 317 of file SP2.h.
Referenced by RenderPolice().
float SP2::EscapeCarMove
Definition at line 323 of file SP2.h.
Referenced by Init(), RenderPolice(), and Update().
bool SP2::EscapeEnd
Definition at line 324 of file SP2.h.
Referenced by EscapeSteal(), Init(), Render(), RenderPlayer(), RenderWorld(), and Update().
float SP2::ExitDoorSlide private
Definition at line 396 of file SP2.h.
Referenced by DoorSlide(), Init(), and RenderWorld().
float SP2::ExplosionScale
Definition at line 325 of file SP2.h.
Referenced by Init(), Render(), RenderWorld(), and Update().
CReadFromText SP2::FNB
Definition at line 284 of file SP2.h.
Referenced by CheckItem(), Init(), ItemMissing(), NPCShop(), RenderFNB(), and UIupdates().
float SP2::FPS private
Definition at line 343 of file SP2.h.
std::string SP2::FPS_count private
Definition at line 372 of file SP2.h.
Referenced by RenderScreenUI(), and UIupdates().
CReadFromText SP2::fridge
Definition at line 281 of file SP2.h.
Referenced by BoundsCheck(), BoundsCheckTrolley(), BulletCollision(), BulletCollisionEnemy(), Init(), and RenderFridge().
bool SP2::GameEndStaff private
Definition at line 355 of file SP2.h.
Referenced by Init(), Render(), and UIupdates().
bool SP2::GameEndSteal private
Definition at line 356 of file SP2.h.
Referenced by Init(), Render(), and Update().
bool SP2::GameEndStealLose private
Definition at line 357 of file SP2.h.
Referenced by Init(), Render(), and Update().
CNPC SP2::guard
Definition at line 306 of file SP2.h.
Referenced by BoundsCheck(), Init(), NPCwalk(), and RenderCharacter().
std::string SP2::GuardTut private
Definition at line 390 of file SP2.h.
float SP2::GunOffset
Definition at line 328 of file SP2.h.
Referenced by Init(), RenderPlayer(), and Update().
float SP2::GunSwing
Definition at line 329 of file SP2.h.
Referenced by Init(), RenderPlayer(), and Update().
std::string SP2::HP private
Definition at line 376 of file SP2.h.
Referenced by UIupdates().
bool SP2::Instruct private
Definition at line 371 of file SP2.h.
Referenced by Init(), MenuUpdate(), and RenderScreenUI().
std::string SP2::INSTRUCTIONS1 private
Definition at line 380 of file SP2.h.
Referenced by RenderScreenUI().
std::string SP2::INSTRUCTIONS2 private
Definition at line 381 of file SP2.h.
Referenced by RenderScreenUI().
std::string SP2::INSTRUCTIONS3 private
Definition at line 382 of file SP2.h.
Referenced by RenderScreenUI().
std::string SP2::INSTRUCTIONS4 private
Definition at line 383 of file SP2.h.
Referenced by RenderScreenUI().
std::string SP2::ItemName private
Definition at line 385 of file SP2.h.
Referenced by CheckItem(), RenderScreenUI(), UIupdates(), and Update().
std::string SP2::ItemPrice private
Definition at line 387 of file SP2.h.
Referenced by RenderScreenUI(), and UIupdates().
CReadFromText SP2::Lamp
Definition at line 292 of file SP2.h.
Referenced by Init(), and RenderBuilding().
float SP2::LeftStaffDoorSlide private
Definition at line 399 of file SP2.h.
Referenced by DoorSlide(), Init(), and RenderWorld().
float SP2::LengthY private
Definition at line 403 of file SP2.h.
Referenced by Init(), and RenderItemMissing().
Light SP2::lights[10] private
Definition at line 414 of file SP2.h.
Referenced by Init(), LightsReset(), MenuUpdate(), Render(), and Stealing().
int SP2::Lightswitch
Definition at line 321 of file SP2.h.
Referenced by LightsReset(), MenuUpdate(), SP2(), and Stealing().
CReadFromText SP2::Locker
Definition at line 293 of file SP2.h.
Referenced by Init(), and RenderBuilding().
vector<CCollisionBounds*> SP2::LockerBounds
Definition at line 301 of file SP2.h.
Referenced by BoundsCheck(), Init(), UIupdates(), and Update().
unsigned SP2::m_parameters[U_TOTAL] private
Definition at line 340 of file SP2.h.
Referenced by Init(), LightsReset(), MenuUpdate(), Render(), RenderMesh(), RenderText(), RenderTextOnScreen(), and Stealing().
unsigned SP2::m_programID private
Definition at line 339 of file SP2.h.
Referenced by Exit(), and Init().
unsigned SP2::m_vertexArrayID private
Definition at line 337 of file SP2.h.
Referenced by Exit(), and Init().
bool SP2::MenuKey private
Definition at line 401 of file SP2.h.
Referenced by Init(), MainMenu(), MenuUpdate(), Render(), and Update().
float SP2::MenuLimit
Definition at line 327 of file SP2.h.
Referenced by MenuUpdate().
int SP2::MenuState
Definition at line 326 of file SP2.h.
Referenced by Init(), MainMenu(), and MenuUpdate().
Mesh* SP2::meshList[NUM_GEOMETRY] private
Definition at line 338 of file SP2.h.
Referenced by CheckOut(), Exit(), Init(), MainMenu(), Render(), RenderAnimate(), RenderAnimate2(), RenderAnimateGuard(), RenderBasicModel(), RenderBuilding(), RenderCashier(), RenderCashierModel(), RenderFNB(), RenderFridge(), RenderItemMissing(), RenderPlayer(), RenderPolice(), RenderScreenUI(), RenderShelves(), RenderSkybox(), RenderWorld(), Trolley(), and TrolleyUpdate().
string SP2::missinglist private
Definition at line 361 of file SP2.h.
Referenced by ItemMissing().
MS SP2::modelStack private
Definition at line 412 of file SP2.h.
Referenced by CheckOut(), Render(), RenderAnimate(), RenderAnimate2(), RenderAnimateGuard(), RenderBasicModel(), RenderBuilding(), RenderCashier(), RenderCashierModel(), RenderCharacter(), RenderFNB(), RenderFridge(), RenderMesh(), RenderPlayer(), RenderPolice(), RenderShelves(), RenderSkybox(), RenderText(), RenderTextOnScreen(), RenderUI(), RenderWorld(), Trolley(), and TrolleyUpdate().
std::string SP2::MONEY private
Definition at line 378 of file SP2.h.
Referenced by RenderScreenUI(), and UIupdates().
Csounds SP2::MusicPlayer
Definition at line 333 of file SP2.h.
Referenced by CheckOut(), EscapeSteal(), Exit(), Init(), MenuUpdate(), and Update().
string SP2::nameofitem[10] private
Definition at line 362 of file SP2.h.
Referenced by ItemMissing().
int SP2::noofitem[10] private
Definition at line 363 of file SP2.h.
Referenced by ItemMissing().
CNPC SP2::npc
Definition at line 305 of file SP2.h.
Referenced by Init(), and NPCwalk().
bool SP2::NPC1idle private
Definition at line 349 of file SP2.h.
Referenced by BoundsCheck(), and Init().
bool SP2::NPC2idle private
Definition at line 350 of file SP2.h.
Referenced by BoundsCheck(), and Init().
bool SP2::NPC3idle private
Definition at line 351 of file SP2.h.
Referenced by BoundsCheck(), and Init().
bool SP2::paid private
Definition at line 353 of file SP2.h.
CNPC SP2::patroler
Definition at line 309 of file SP2.h.
Referenced by BoundsCheck(), BoundsCheckTrolley(), and Init().
bool SP2::paying private
Definition at line 352 of file SP2.h.
Referenced by CheckOut().
bool SP2::PInstruct private
Definition at line 369 of file SP2.h.
Referenced by Init(), RenderScreenUI(), and Update().
CCharacter SP2::player
Definition at line 310 of file SP2.h.
Referenced by BoundsCheck(), BulletCollisionEnemy(), CheckItem(), CheckOut(), EscapeSteal(), ItemMissing(), Render(), RenderItemMissing(), RenderPlayer(), RenderScreenUI(), Trolley(), TrolleyUpdate(), UIupdates(), UnpaidItems(), and Update().
bool SP2::playeridle private
Definition at line 348 of file SP2.h.
Referenced by BoundsCheck(), BoundsCheckTrolley(), Init(), NPCShop(), and NPCwalk().
CReadFromText SP2::Police
Definition at line 285 of file SP2.h.
Referenced by BulletCollision(), BulletCollisionEnemy(), Init(), RenderPolice(), and Update().
bool SP2::police
Definition at line 320 of file SP2.h.
Referenced by BoundsCheck(), BoundsCheckTrolley(), CheckOut(), EscapeSteal(), Init(), LightsReset(), Render(), RenderFNB(), RenderPlayer(), Stealing(), UIupdates(), UnpaidItems(), and Update().
CPolice SP2::police1
Definition at line 313 of file SP2.h.
Referenced by PoliceShoot(), RenderPolice(), and Update().
CPolice SP2::police2
Definition at line 314 of file SP2.h.
Referenced by RenderPolice(), and Update().
CPolice SP2::police3
Definition at line 315 of file SP2.h.
Referenced by RenderPolice(), and Update().
CPolice SP2::police4
Definition at line 316 of file SP2.h.
Referenced by RenderPolice(), and Update().
vector<CBullet*> SP2::Policebullet
Definition at line 295 of file SP2.h.
Referenced by PoliceShoot(), Render(), and Update().
CReadFromText SP2::PoliceCol
Definition at line 286 of file SP2.h.
Referenced by BulletCollisionEnemy(), and Init().
float SP2::PoliceInstructTimer private
Definition at line 367 of file SP2.h.
Referenced by RenderScreenUI(), and Update().
CReadFromText SP2::PoliceMan
Definition at line 287 of file SP2.h.
Referenced by BulletCollision(), Init(), PoliceShoot(), RenderPolice(), and Update().
MS SP2::projectionStack private
Definition at line 412 of file SP2.h.
Referenced by Init(), RenderMesh(), RenderText(), RenderTextOnScreen(), RenderUI(), and Update().
int SP2::RandomItem
Definition at line 334 of file SP2.h.
Referenced by Init(), and ItemMissing().
float SP2::RightStaffDoorSlide private
Definition at line 398 of file SP2.h.
Referenced by DoorSlide(), Init(), and RenderWorld().
std::string SP2::ROLE private
Definition at line 379 of file SP2.h.
Referenced by Init(), RenderScreenUI(), and Update().
float SP2::rotateAngle private
Definition at line 342 of file SP2.h.
Referenced by Init().
CCameraSecurity SP2::Security1 private
Definition at line 408 of file SP2.h.
Referenced by Init(), Render(), and Update().
CCameraSecurity SP2::Security2 private
Definition at line 409 of file SP2.h.
Referenced by Init(), Render(), and Update().
CReadFromText SP2::shelve
Definition at line 279 of file SP2.h.
Referenced by BoundsCheck(), BoundsCheckTrolley(), BulletCollision(), BulletCollisionEnemy(), Init(), and RenderShelves().
CBullet SP2::shoot
Definition at line 296 of file SP2.h.
Referenced by CheckItem(), UIupdates(), and Update().
CNPC SP2::shopper
Definition at line 307 of file SP2.h.
Referenced by BoundsCheck(), BoundsCheckTrolley(), DoorSlide(), Init(), NPCShop(), NPCwalk(), RenderCharacter(), and RenderScreenUI().
CNPC SP2::shopperTwo
Definition at line 308 of file SP2.h.
Referenced by BoundsCheck(), Init(), NPCShop(), NPCwalk(), and RenderCharacter().
bool SP2::ShopStaff private
Definition at line 354 of file SP2.h.
Referenced by CheckOut(), Init(), Render(), UIupdates(), and Update().
std::string SP2::ShopTut private
Definition at line 389 of file SP2.h.
float SP2::ShutterDoorOpen private
Definition at line 397 of file SP2.h.
Referenced by Init(), RenderWorld(), and ShutterOpen().
bool SP2::SInstruct private
Definition at line 370 of file SP2.h.
Referenced by Init(), RenderScreenUI(), and Update().
float SP2::StaffInstructTimer private
Definition at line 368 of file SP2.h.
Referenced by RenderScreenUI(), and Update().
std::string SP2::STAM private
Definition at line 377 of file SP2.h.
Referenced by UIupdates().
std::string SP2::Target private
Definition at line 375 of file SP2.h.
Referenced by UIupdates().
std::string SP2::TheifTut private
Definition at line 388 of file SP2.h.
std::string SP2::TITLE private
Definition at line 384 of file SP2.h.
float SP2::translate private
Definition at line 345 of file SP2.h.
Referenced by Animate(), Init(), RenderAnimate(), RenderAnimate2(), and RenderAnimateGuard().
float SP2::translateY private
Definition at line 346 of file SP2.h.
Referenced by Animate(), Init(), RenderAnimate(), RenderAnimate2(), and RenderAnimateGuard().
CTrolley SP2::trolley
Definition at line 311 of file SP2.h.
Referenced by BoundsCheck(), Trolley(), TrolleyUpdate(), and UIupdates().
CBullet SP2::Trolleyz
Definition at line 297 of file SP2.h.
Referenced by Render(), Trolley(), and Update().
bool SP2::UpdateItemMissing private
Definition at line 360 of file SP2.h.
Referenced by Init(), and Render().
vector<CCollisionBounds*> SP2::VanBounds
Definition at line 300 of file SP2.h.
Referenced by BoundsCheck(), BoundsCheckTrolley(), BulletCollisionEnemy(), EscapeSteal(), Init(), and UIupdates().
MS SP2::viewStack private
Definition at line 412 of file SP2.h.
Referenced by Render(), RenderMesh(), RenderText(), RenderTextOnScreen(), and RenderUI().
bool SP2::walk private
Definition at line 347 of file SP2.h.
Referenced by Animate(), and Init().
std::string SP2::XPos private
Definition at line 373 of file SP2.h.
Referenced by UIupdates().
std::string SP2::ZPos private
Definition at line 374 of file SP2.h.
Referenced by UIupdates().
The documentation for this class was generated from the following files:
MyGraphics/Source/SP2.h
MyGraphics/Source/SP2.cpp