My Application: CNPC Class Reference
CNPC Class Reference
#include <NPC.h>
Public Member Functions
CNPC (void)
~CNPC (void)
void setName (string name)
void setPosX (float x)
void setPosZ (float z)
void setSpeed (float speed)
void setDirection (int state)
void SetRot (float rot)
void setPath (int node)
void setCheckpoints (int n, float point)
void setCurrentState (int state)
void TestAIPath (void)
void ShopPathing (int n, bool idle)
string getName (void)
float getPosX (void)
float getPosZ (void)
float getSpeed (void)
float getRot (void)
int getDirection (void)
int getPath (void)
float getCheckpoints (int n)
int getCurrentState (void)
int RandNumGen (int minNum, int maxNum)
void Checkout ()
void Steal ()
void setShop (bool input)
bool getShop ()
void respawn ()
void ReadTextFilePath (const char *filename)
CNPC * GetNPCPos (const int selection)
Data Fields
int maxItem
bool cashIn
bool exitMart
bool enterMart
Private Attributes
string CharName
float CharSpeed
float CharPosX
float CharPosZ
float CharRot
int Direction
int Path
int CurrentState
float Checkpoints [20]
vector< CNPC * > npc_list
bool shop
Detailed Description
Definition at line 14 of file NPC.h.
Constructor & Destructor Documentation
CNPC::CNPC (void)
Definition at line 4 of file NPC.cpp.
References cashIn, CharName, CharPosX, CharPosZ, CharRot, CharSpeed, enterMart, exitMart, maxItem, Path, and shop.
Referenced by ReadTextFilePath().
CNPC::~CNPC (void)
Definition at line 20 of file NPC.cpp.
Member Function Documentation
void CNPC::Checkout ()
Definition at line 423 of file NPC.cpp.
References cashIn, exitMart, getPosX(), getPosZ(), getRot(), setPosX(), setPosZ(), and SetRot().
Referenced by SP2::NPCShop().
float CNPC::getCheckpoints (int n)
Definition at line 399 of file NPC.cpp.
References Checkpoints.
Referenced by ShopPathing().
int CNPC::getCurrentState (void)
Definition at line 409 of file NPC.cpp.
References CurrentState.
int CNPC::getDirection (void)
Definition at line 69 of file NPC.cpp.
References Direction.
Referenced by TestAIPath().
string CNPC::getName (void)
Definition at line 44 of file NPC.cpp.
References CharName.
CNPC * CNPC::GetNPCPos (const int selection)
Definition at line 181 of file NPC.cpp.
References npc_list.
Referenced by ShopPathing().
int CNPC::getPath (void)
Definition at line 176 of file NPC.cpp.
References Path.
Referenced by ShopPathing().
float CNPC::getPosX (void)
Definition at line 49 of file NPC.cpp.
References CharPosX.
Referenced by SP2::BoundsCheck(), SP2::BoundsCheckTrolley(), Checkout(), SP2::NPCShop(), SP2::RenderCharacter(), SP2::RenderScreenUI(), ShopPathing(), and TestAIPath().
float CNPC::getPosZ (void)
Definition at line 54 of file NPC.cpp.
References CharPosZ.
Referenced by SP2::BoundsCheck(), SP2::BoundsCheckTrolley(), Checkout(), SP2::NPCShop(), SP2::RenderCharacter(), SP2::RenderScreenUI(), ShopPathing(), and TestAIPath().
float CNPC::getRot (void)
Definition at line 79 of file NPC.cpp.
References CharRot.
Referenced by Checkout(), SP2::NPCShop(), SP2::RenderCharacter(), ShopPathing(), and TestAIPath().
bool CNPC::getShop ()
Definition at line 513 of file NPC.cpp.
References shop.
float CNPC::getSpeed (void)
Definition at line 59 of file NPC.cpp.
References CharSpeed.
int CNPC::RandNumGen (int minNum, int maxNum)
Definition at line 414 of file NPC.cpp.
void CNPC::ReadTextFilePath (const char * filename)
Definition at line 186 of file NPC.cpp.
References CNPC(), npc_list, and setCheckpoints().
Referenced by SP2::Init().
void CNPC::respawn ()
Definition at line 517 of file NPC.cpp.
References cashIn, maxItem, setPosX(), setPosZ(), and SetRot().
Referenced by SP2::NPCShop().
void CNPC::setCheckpoints (int n, float point)
Definition at line 394 of file NPC.cpp.
References Checkpoints.
Referenced by ReadTextFilePath().
void CNPC::setCurrentState (int state)
Definition at line 404 of file NPC.cpp.
References CurrentState.
void CNPC::setDirection (int state)
Definition at line 64 of file NPC.cpp.
References Direction.
Referenced by TestAIPath().
void CNPC::setName (string name)
Definition at line 24 of file NPC.cpp.
References CharName.
Referenced by SP2::Init().
void CNPC::setPath (int node)
Definition at line 171 of file NPC.cpp.
References Path.
Referenced by ShopPathing().
void CNPC::setPosX (float x)
Definition at line 29 of file NPC.cpp.
References CharPosX.
Referenced by Checkout(), SP2::Init(), respawn(), ShopPathing(), and TestAIPath().
void CNPC::setPosZ (float z)
Definition at line 34 of file NPC.cpp.
References CharPosZ.
Referenced by Checkout(), SP2::Init(), respawn(), ShopPathing(), and TestAIPath().
void CNPC::SetRot (float rot)
Definition at line 74 of file NPC.cpp.
References CharRot.
Referenced by Checkout(), respawn(), ShopPathing(), and TestAIPath().
void CNPC::setShop (bool input)
Definition at line 509 of file NPC.cpp.
References shop.
Referenced by SP2::NPCShop().
void CNPC::setSpeed (float speed)
Definition at line 39 of file NPC.cpp.
References CharSpeed.
void CNPC::ShopPathing (int n, bool idle)
Definition at line 234 of file NPC.cpp.
References cashIn, getCheckpoints(), GetNPCPos(), getPath(), getPosX(), getPosZ(), getRot(), setPath(), setPosX(), setPosZ(), SetRot(), and shop.
Referenced by SP2::NPCwalk().
void CNPC::Steal ()
Definition at line 506 of file NPC.cpp.
void CNPC::TestAIPath (void)
Definition at line 84 of file NPC.cpp.
References getDirection(), getPosX(), getPosZ(), getRot(), setDirection(), setPosX(), setPosZ(), and SetRot().
Referenced by SP2::NPCwalk().
Field Documentation
bool CNPC::cashIn
Definition at line 61 of file NPC.h.
Referenced by Checkout(), CNPC(), SP2::NPCShop(), respawn(), and ShopPathing().
string CNPC::CharName private
Definition at line 17 of file NPC.h.
Referenced by CNPC(), getName(), and setName().
float CNPC::CharPosX private
Definition at line 19 of file NPC.h.
Referenced by CNPC(), getPosX(), and setPosX().
float CNPC::CharPosZ private
Definition at line 20 of file NPC.h.
Referenced by CNPC(), getPosZ(), and setPosZ().
float CNPC::CharRot private
Definition at line 21 of file NPC.h.
Referenced by CNPC(), getRot(), and SetRot().
float CNPC::CharSpeed private
Definition at line 18 of file NPC.h.
Referenced by CNPC(), getSpeed(), and setSpeed().
float CNPC::Checkpoints[20] private
Definition at line 25 of file NPC.h.
Referenced by getCheckpoints(), and setCheckpoints().
int CNPC::CurrentState private
Definition at line 24 of file NPC.h.
Referenced by getCurrentState(), and setCurrentState().
int CNPC::Direction private
Definition at line 22 of file NPC.h.
Referenced by getDirection(), and setDirection().
bool CNPC::enterMart
Definition at line 63 of file NPC.h.
Referenced by CNPC(), SP2::DoorSlide(), and SP2::NPCShop().
bool CNPC::exitMart
Definition at line 62 of file NPC.h.
Referenced by Checkout(), CNPC(), and SP2::DoorSlide().
int CNPC::maxItem
Definition at line 60 of file NPC.h.
Referenced by CNPC(), SP2::NPCShop(), and respawn().
vector<CNPC*> CNPC::npc_list private
Definition at line 26 of file NPC.h.
Referenced by GetNPCPos(), and ReadTextFilePath().
int CNPC::Path private
Definition at line 23 of file NPC.h.
Referenced by CNPC(), getPath(), and setPath().
bool CNPC::shop private
Definition at line 28 of file NPC.h.
Referenced by CNPC(), getShop(), setShop(), and ShopPathing().
The documentation for this class was generated from the following files:
MyGraphics/Source/NPC.h
MyGraphics/Source/NPC.cpp