My Application: CCharacter Class Reference
CCharacter Class Reference
#include <Character.h>
Public Member Functions
CCharacter (void)
~CCharacter (void)
void setMoney (double cash)
void setHealth (int hp)
void setStamina (int stam)
void setBullets (int ammo)
void setDetection (float detect)
void setInventory (string name, double price)
void setClass (string job)
void dropItem (string itemname)
void sellItems (int n)
void setInventoryCap (int size)
double getMoney (void)
int getHealth (void)
int getStamina (void)
int getBullets (void)
float getDetection (void)
CItem * getInventory (int n)
string getClass (void)
int returnInvenSize ()
int getInventoryCap (void)
Data Fields
bool unpaiditems
bool trolley
bool trolleyDrop
bool Align
bool Takeitems
Private Attributes
double money
int health
int stamina
int bullets
float detection
vector< CItem * > inven_list
int inventoryCap
string career
Detailed Description
Definition at line 17 of file Character.h.
Constructor & Destructor Documentation
CCharacter::CCharacter (void)
Definition at line 13 of file Character.cpp.
References Align, bullets, career, detection, health, inventoryCap, money, stamina, trolley, trolleyDrop, and unpaiditems.
CCharacter::~CCharacter (void)
Definition at line 29 of file Character.cpp.
Member Function Documentation
void CCharacter::dropItem (string itemname)
Definition at line 96 of file Character.cpp.
References getInventory(), CItem::getItemName(), inven_list, and returnInvenSize().
Referenced by SP2::CheckItem().
int CCharacter::getBullets (void)
string CCharacter::getClass (void)
Definition at line 83 of file Character.cpp.
References career.
float CCharacter::getDetection (void)
Definition at line 78 of file Character.cpp.
References detection.
int CCharacter::getHealth (void)
Definition at line 68 of file Character.cpp.
References health.
Referenced by SP2::RenderScreenUI(), and SP2::UIupdates().
CItem * CCharacter::getInventory (int n)
Definition at line 115 of file Character.cpp.
References inven_list.
Referenced by SP2::CheckOut(), dropItem(), SP2::EscapeSteal(), SP2::RenderScreenUI(), and SP2::TrolleyUpdate().
int CCharacter::getInventoryCap (void)
Definition at line 130 of file Character.cpp.
References inventoryCap.
Referenced by SP2::CheckItem(), and SP2::RenderScreenUI().
double CCharacter::getMoney (void)
Definition at line 63 of file Character.cpp.
References money.
Referenced by SP2::UIupdates().
int CCharacter::getStamina (void)
Definition at line 73 of file Character.cpp.
References stamina.
Referenced by SP2::UIupdates(), and Camera3::Update().
int CCharacter::returnInvenSize ()
Definition at line 120 of file Character.cpp.
References inven_list.
Referenced by SP2::CheckItem(), SP2::CheckOut(), dropItem(), SP2::EscapeSteal(), SP2::RenderScreenUI(), SP2::TrolleyUpdate(), and SP2::UnpaidItems().
void CCharacter::sellItems (int n)
Definition at line 110 of file Character.cpp.
References inven_list.
Referenced by SP2::CheckOut(), and SP2::EscapeSteal().
void CCharacter::setBullets (int ammo)
Definition at line 43 of file Character.cpp.
References bullets.
void CCharacter::setClass (string job)
Definition at line 58 of file Character.cpp.
References career.
void CCharacter::setDetection (float detect)
Definition at line 53 of file Character.cpp.
References detection.
void CCharacter::setHealth (int hp)
Definition at line 33 of file Character.cpp.
References health.
Referenced by SP2::BulletCollisionEnemy().
void CCharacter::setInventory (string name, double price)
Definition at line 88 of file Character.cpp.
References inven_list, CItem::setItemName(), and CItem::setItemPrice().
Referenced by SP2::CheckItem().
void CCharacter::setInventoryCap (int size)
Definition at line 125 of file Character.cpp.
References inventoryCap.
Referenced by SP2::Trolley().
void CCharacter::setMoney (double cash)
Definition at line 38 of file Character.cpp.
References money.
Referenced by SP2::CheckOut(), and SP2::EscapeSteal().
void CCharacter::setStamina (int stam)
Definition at line 48 of file Character.cpp.
References stamina.
Referenced by Camera3::Update().
Field Documentation
bool CCharacter::Align
Definition at line 56 of file Character.h.
Referenced by CCharacter().
int CCharacter::bullets private
Definition at line 23 of file Character.h.
Referenced by CCharacter(), and setBullets().
string CCharacter::career private
Definition at line 27 of file Character.h.
Referenced by CCharacter(), getClass(), and setClass().
float CCharacter::detection private
Definition at line 24 of file Character.h.
Referenced by CCharacter(), getDetection(), and setDetection().
int CCharacter::health private
Definition at line 21 of file Character.h.
Referenced by CCharacter(), getHealth(), and setHealth().
vector<CItem* > CCharacter::inven_list private
Definition at line 25 of file Character.h.
Referenced by dropItem(), getInventory(), returnInvenSize(), sellItems(), and setInventory().
int CCharacter::inventoryCap private
Definition at line 26 of file Character.h.
Referenced by CCharacter(), getInventoryCap(), and setInventoryCap().
double CCharacter::money private
Definition at line 20 of file Character.h.
Referenced by CCharacter(), getMoney(), and setMoney().
int CCharacter::stamina private
Definition at line 22 of file Character.h.
Referenced by CCharacter(), getStamina(), and setStamina().
bool CCharacter::Takeitems
Definition at line 57 of file Character.h.
Referenced by SP2::CheckItem().
bool CCharacter::trolley
Definition at line 54 of file Character.h.
Referenced by CCharacter(), SP2::RenderPlayer(), SP2::Trolley(), SP2::TrolleyUpdate(), and SP2::UIupdates().
bool CCharacter::trolleyDrop
Definition at line 55 of file Character.h.
Referenced by CCharacter(), SP2::Trolley(), and SP2::TrolleyUpdate().
bool CCharacter::unpaiditems
Definition at line 53 of file Character.h.
Referenced by CCharacter(), and SP2::UnpaidItems().
The documentation for this class was generated from the following files:
MyGraphics/Source/Character.h
MyGraphics/Source/Character.cpp