My Application: CCameraSecurity Class Reference
CCameraSecurity Class Reference
#include <CameraSecurity.h>
Public Member Functions
CCameraSecurity (void)
~CCameraSecurity (void)
virtual void Init (const Vector3 &pos, const Vector3 &target, const Vector3 &up)
virtual void Update (double dt)
Public Member Functions inherited from Camera
Camera ()
~Camera ()
virtual void Reset ()
Data Fields
Vector3 defaultPosition
Vector3 defaultTarget
Vector3 defaultUp
Application test
float Limit
Data Fields inherited from Camera
Vector3 position
Vector3 target
Vector3 up
Detailed Description
Definition at line 19 of file CameraSecurity.h.
Constructor & Destructor Documentation
CCameraSecurity::CCameraSecurity (void)
Definition at line 13 of file CameraSecurity.cpp.
References Limit.
CCameraSecurity::~CCameraSecurity (void)
Definition at line 19 of file CameraSecurity.cpp.
Member Function Documentation
void CCameraSecurity::Init (const Vector3 & pos, const Vector3 & target, const Vector3 & up) virtual
Reimplemented from Camera.
Definition at line 23 of file CameraSecurity.cpp.
References Vector3::Cross(), defaultPosition, defaultTarget, defaultUp, Vector3::Normalize(), Vector3::Normalized(), Camera::position, Camera::target, and Vector3::y.
Referenced by SP2::Init().
void CCameraSecurity::Update (double dt) virtual
Reimplemented from Camera.
Definition at line 34 of file CameraSecurity.cpp.
References Application::getPosX(), Application::getPosY(), Limit, Application::mousePos(), Camera::position, Mtx44::SetToRotation(), Camera::target, test, and Camera::up.
Referenced by SP2::Update().
Field Documentation
Vector3 CCameraSecurity::defaultPosition
Definition at line 22 of file CameraSecurity.h.
Referenced by Init().
Vector3 CCameraSecurity::defaultTarget
Definition at line 23 of file CameraSecurity.h.
Referenced by Init().
Vector3 CCameraSecurity::defaultUp
Definition at line 24 of file CameraSecurity.h.
Referenced by Init().
float CCameraSecurity::Limit
Definition at line 32 of file CameraSecurity.h.
Referenced by CCameraSecurity(), and Update().
Application CCameraSecurity::test
Definition at line 31 of file CameraSecurity.h.
Referenced by Update().
The documentation for this class was generated from the following files:
MyGraphics/Source/CameraSecurity.h
MyGraphics/Source/CameraSecurity.cpp